// Diaglogue taken from https://github.com/telefang/telefang/tree/patch/gfx/evolve

export const diaglogue: string[] = [
    `Hey, long time no see! Wanna try a Denjuu Quiz? <Q>Okay<|>No</Q><*A>`,
    `How many ways are there to evolve a Denjuu? <Q>3 ways!<|>4 ways!</Q><*A>`,
    `Do you hate quizzes? <Q>Yes<|>I don't!</Q><*A>`,
    `Well done, <&name>! That's correct!!`,
    `Aww, come on! You got it wrong!!`,
    `Is it because you hate using your brain???`,
    `Next time, then. See ya later!!`,

    `What's up?! Wanna try a Denjuu Quiz? <Q>Sure<|>No thanks</Q><*A>`,
    `There are 2 versions of Telefang! Power, and what else? <Q>Hyper<|>Speed</Q><*A>`,
    `Oh, are you busy right now? <Q> Kind of... <|> Well, not really. </Q><*A>`,
    `Close but no cigar! Better luck next time!!`,
    `I wonder if that was a bit too easy. Everyone knows that!!`,
    `Sorry! I didn't mean to interrupt!!`,
    `Then what's the problem? Jerk!!`,

    `Are you bored? How about a Denjuu Quiz? <Q>Sure<|>Nah</Q><*A>`,
    `What do you call a Denjuu user? <Q>T-Fanger<|>B-Fanger</Q><*A>`,
    `You don't want to? Is it... because you hate me? <Q> Of course not! <|> Well, actually... </Q><*A>`,
    `Exactly! That's correct!!`,
    `Whaaat? I can't believe you'd get that wrong!!`,
    `That's good! I don't know what I'd do if you did!!`,
    `Wh-- What?! Oh noo... What did I do wrong?!!`,

    `A-ha! I betcha really wanna do a Denjuu Quiz right now! <Q>Yeah!<|>No.</Q><*A>`,
    `What button do you hold to run? <Q> The A Button. <|> The B Button. </Q><*A>`,
    `Are you suuure you don't wanna try? <Q> In your dreams. <|> Maybe next time! </Q><*A>`,
    `Seriously??? There's no way that works!!`,
    `That's right, <&name>! Well done!!`,
    `Why not?! You don't have to say it like that!!`,
    `Really? You'd better promise then!!`,

    `You picked up the phone, so it's time for a Denjuu Quiz! <Q>Alright!<|>No thanks!</Q><*A>`,
    `True or false? Denjuu have their own zodiac. <Q>True<|>False</Q><*A>`,
    `State your reason! <Q>I'm tired<|>Reasons.</Q><*A>`,
    `You got it! That was easy!!`,
    `You didn't know? You have to pay attention to these things!!`,
    `I see... I know the feeling. Maybe next time, right??`,
    `Has there ever been a more half-hearted answer? Get it together, man!!`,

    `I know! You wanna try a Denjuu Quiz, don't you? <Q>Sure<|>Nope</Q><*A>`,
    `What does the word "Telefang" refer to? <Q>A Denjuu<|>A battle</Q><*A>`,
    `You don't wanna? Don't you care what I have to say? <Q> You got me. <|> That's not it! </Q><*A>`,
    `I don't know anyone named that! Did you get it wrong on purpose??`,
    `Obviously! I'm pretty sure everyone knows that..`,
    `I see! Fine then, be that way!!!!`,
    `Yeah, I knew you wouldn't do such a thing!!`,

    `How would you feel about a Denjuu Quiz? <Q>Pumped<|>Disinclined</Q><*A>`,
    `What separates the Denjuu World from the humans' is called the curtain of...? <Q>Darkness<|>Sunlight</Q><*A>`,
    `What's the matter? Feeling unsure of yourself? <Q>No<|>I just don't wanna</Q><*A>`,

    `C'mon, you gotta pay attention to what people tell ya!!`,
    `Yeah, that wouldn't be it, would it? I mean, you're <&name>, after all!!`,
    `Oh, okay. I won't force you. Sorry....`,

    `Hey, are you free? Wanna try a Denjuu Quiz? <Q>Sure<|>No thanks</Q><*A>`,
    `Is there a place in the Shop to deposit your money? <Q>Yes<|>No</Q><*A>`,
    `You don't like quizzes? <Q>That's not it<|>I don't</Q><*A>`,
    `Nope! Sorry to say, but there's no such thing!!`,
    `Correct! When you're carrying a lot of money you'd want to deposit it somewhere, though, wouldn't you??`,
    `Okay, well, we can do it next time we get the chance!!`,
    `Oh, sorry! Don't be mad, okay? I won't quiz you anymore..`,

    `Denjuu Quiz! I won't let you say no! <Q>Okay<|>No</Q><*A>`,
    `What's the name of the Den- juu that nods off a lot? <Q>Netaro<|>Nejiro</Q><*A>`,
    `No?! You feeling tired? <Q>Yeah<|>Not really</Q><*A>`,
    `That's right! Not a very hard question, is it??`,
    `What the hey?! Use your brain before you answer!!`,
    `This isn't the time to be half asleep! Get it together!!`,
    `Not really?! "Not really", he says! Now you've done it! I'm mad!!`,

    `Don't say anything... You want to do a Denjuu Quiz! <Q>Sure<|>No</Q><*A>`,
    `How many friends can you call when you have 3 bars of reception? <Q>3 friends<|>2 friends</Q><*A>`,
    `What? Why?! That's cold, man! <Q>Oh, really?<|>Sorry...</Q><*A>`,
    `Nah, the Denjuu following you doesn't count!!`,
    `It's such a simple little fact, but it's important to remember!!`,
    `Grrr!!! That's it! Who needs you, anyway!!`,
    `You don't need to apologize! I'll let you off this time..`,

    `I know it's sudden, but are you up for a Denjuu Quiz? <Q>Sure<|>Nah</Q><*A>`,
    `If you put your phone on silent, what happens if it goes off? <Q> It makes no sound. <|> It hangs up. </Q><*A>`,
    `But in reality, you want to, right? <Q>Yeah...<|>Not really</Q><*A>`,
    `That's right! It's important to mind your manners..`,
    `No, obviously that's not right. Try it out and see!!`,
    `I knew it! You don't have to be embarrassed about it, you know..`,
    `I see... Oh well! Another time, then!!`,

    `Would you like to do a Denjuu Quiz? <Q>Yeah!<|>No</Q><*A>`,
    `What do you need to enter the Denjuu World? <Q>A G-Shot!<|>A D-Shot!</Q><*A>`,
    `Any particular reason? You can tell me. <Q>Actually...<|>Not really</Q><*A>`,
    `That's not quite right... Think it over and try again!!`,
    `That's right! You can't do anything without a D-Shot!!`,
    `Oh, I see... I won't bother you, then..`,
    `Let's do it next time we get the chance, then. See ya!!`,

    `You picked up and all, so we might as well do a Denjuu Quiz, right? <Q>Sure!<|>No thanks</Q><*A>`,
    `Does the <bold>Map<normal> show you places you haven't been? <Q>It doesn't<|>It does</Q><*A>`,
    `Don't worry! It won't be a difficult one. <Q>But...<|>Well, okay.</Q><*A>`,
    `That's right! You gotta walk around and see lots of different places!!`,
    `Nah, it doesn't show you those. Don't let that trip you up!!`,
    `I get it, but you should really try to challenge yourself!!`,
    `Oh, sorry! Let's do it later. I've gotta go see someone!!`,

    `Right! I think it's about time for a Denjuu Quiz! <Q>Okay<|>No thanks</Q><*A>`,
    `What does a Denjuu's FD represent? <Q>Distance<|>Friendship</Q><*A>`,
    `I guess it's too early for that, huh. <Q>Yeah<|>Early?</Q><*A>`,
    `You guessed wrong, huh? That seems to happen a lot!!`,
    `Correct! It's surprisingly hard to understand, this FD..`,
    `I see... I'm sorry. Normally I'm not this impatient..`,
    `You don't get what I mean? Ahahah, me neither!!`,

    `I don't really have any- thing to talk about, so how about a Denjuu Quiz? <Q>Sounds good<|>I'll pass</Q><*A>`,
    `Can you steal items from shops? <Q>No<|>Yes</Q><*A>`,
    `Wanna talk about something else then? <Q>Sure!<|>Either way's fine!</Q><*A>`,
    `Right? Obviously you can't..`,
    `If you could, that would be a problem! Of course you can't!!`,
    `Let's see... When prompted like this, I can't really think of anything!!`,
    `Are you tired? You should take a break..`,

    `You seem bored! Wanna try a Denjuu Quiz? <Q>Sure<|>I'm busy</Q><*A>`,
    `Can you make your own ringtones with Melo-D? <Q>No<|>Yes</Q><*A>`,
    `You don't have to pretend you've got things to do! <Q>I'm not!<|>Stop it.</Q><*A>`,
    `But... you can! You didn't know until now??`,
    `That's right! I don't know any hits, though....`,
    `Wait, you were actually busy? I'm sorry!!`,
    `Don't be so angry! It was just a joke....`,

    `<&name>, you're a fan of Denjuu Quizzes, right? <Q>Yeah!<|>Not really</Q><*A>`,
    `What button do you press to talk to people? <Q> The A Button. <|> The B Button. </Q><*A>`,
    `What happened? That's not like you at all! <Q>Really?<|>No, it is.</Q><*A>`,
    `Maybe that was a bit too easy? To a ridiculous degree, huh??`,
    `How could you get a question like this wrong?!!`,
    `It's not! Whatever the task, you always give your all!!`,
    `When did you become such a cold person, <&name>?!!`,

    `I really wanna do a Denjuu Quiz right now! <Q>Alright<|>No thanks</Q><*A>`,
    `Can you change which Denjuu is following you? <Q>You can't!<|>You can!</Q><*A>`,
    `Don't say that! Please! <Q> I said no! <|> If you insist! </Q><*A>`,
    `Haven't you tried yet? How about you give it a shot right now??`,
    `That's entirely right! That's what makes it so interesting, right??`,
    `Fine then! I didn't think you were like that!!`,
    `You’re a good person, <&name>! I really think so!!`,

    `Wanna try a Denjuu Quiz? It won't take long! <Q>Okay<|>Uhh...</Q><*A>`,
    `Is Matsukiyo a boy or a girl? <Q>Boy<|>Girl</Q><*A>`,
    `Huh? What? What does that "uhh" mean? <Q> You tell me! <|> Just messin' with ya! </Q><*A>`,
    `You wouldn't get things wrong about your own friends, after all!!`,
    `C'mon, really?! Looks like a boy to me!!`,
    `Did I say something bad? Sorry! I didn't mean to!!`,
    `Don't scare me like that! I'm nervous enough as it is..`,

    `If I asked you to do a Denjuu Quiz right now, would you get mad? <Q>No<|>Yes</Q><*A>`,
    `Are all T-Fangers guys? <Q>Yes<|>Not at all</Q><*A>`,
    `Really? You'd get mad? You mean it? <Q>Yes<|>Of course not!</Q><*A>`,
    `I don't think so! There are plenty of T-Fanger girls out there!!`,
    `After all, there are girls even among your own T-Fanger friends, right??`,
    `Really? Okay, forget I said anything!!`,
    `Phew! I wouldn't know what to do if you got mad at me!!`,

    `You must be hankering for a Denjuu Quiz by now! <Q>Yeah<|>No thanks</Q><*A>`,
    `What is evolution by gaining experience called? <Q> Natural evolution <|> Standard evolution </Q><*A>`,
    `Do you think that kind of attitude is acceptable?! <Q>Yep!<|>I'm sorry.</Q><*A>`,
    `You know your stuff! Make sure to hold on to that knowledge!!`,
    `Something's not quite right there... You feel it too, don't you??`,
    `You wouldn't like me when I'm angry! I'm serious!!!!`,
    `I'll overlook it this time. But next time, we're definitely doing it!!`,

    `Time for a Denjuu Quiz! I bet you wanna! <Q>I do<|>No way</Q><*A>`,
    `What's it called when you evolve a Denjuu by combining it with a doohickey? <Q> Assembly evolution <|> Augment evolution </Q><*A>`,
    `Yeah, I thought you'd say that. <Q>So you knew?<|>Liar</Q><*A>`,
    `Close, but not quite! Go brush up on evolution!!`,
    `Spot on, huh? You're amazing, you know!!`,
    `Hah! Got you! You're so easy to read, <&name>!!`,
    `I'd never lie! Seriously!!`,

    `How about a Denjuu Quiz for a change? <Q>Sure<|>No thanks</Q><*A>`,
    `What type of evolution requires splicing DNA from another Denjuu? <Q> DNA evolution. <|> Genetic evolution. </Q><*A>`,
    `Well, if you really don't feel like it... <Q> I guess I'll do it <|> Sorry </Q><*A>`,
    `Correct! DNA evolution isn't simple to do, is it??`,
    `Maybe you don't actually know about it yet? I suppose you wouldn't know the answer then....`,
    `I knew you'd come around! Let's do it another time, though!!`,
    `You don't need to apologize. These things happen!!`,

    `It's certainly been a while! May I tempt you with a Denjuu Quiz? <Q>Okay<|>No thanks</Q><*A>`,
    `What does one have to do in order to get a Denjuu's phone number? <Q>Flee<|>Fight</Q><*A>`,
    `Don't you wish to learn more about the Denjuu World? <Q>I do!<|>No.</Q><*A>`,
    `Flee? If you do, you will never get one!!`,
    `Indeed! You get their number by besting them in battle!!`,
    `Very well. When the opportunity next arises, pick up that gauntlet!!`,
    `Please don't say something so sad ever again!!`,

    `I know this is sudden, but which of these do you like the most? <Q> Telefang <|> Exploring towns </Q><*A>`,
    `What do you like about Telefang battles? <Q>Winning<|>Losing</Q><*A>`,
    `What's the most fun part of exploring? <Q> Talking to people. <|> Finding treasure. </Q><*A>`,
    `It's gotta be, right? I feel the same way!!`,
    `That's a bit weird. Most people'd say the opposite!!`,
    `You'll hear lots of new info when talking to people, after all!!`,
    `Yeah, finding something always cheers you right up!!`,

    `Y'know, I've been having these dreams lately... Have you had any? <Q>Yes<|>No</Q><*A>`,
    `Could you tell me what kind of dreams they were? <Q>Sure<|>Why?</Q><*A>`,
    `I've been having them every night! And they're nightmares, too! <Q> What kind? <|> I don't wanna know </Q><*A>`,
    `Ohhh, you're hitting home runs in your dreams? Nice!!`,
    `Well... I'm interested to know what others dream about!!`,
    `Wanna know? Well... I keep dreaming about getting sucked into a whirlpool!!`,
    `Too scary for you? Well, they HAVE made it difficult for me to go to the bathroom alone at night, so....`,

    `Are you having fun in the Denjuu World? <Q>Heck yeah!<|>It's so-so.</Q><*A>`,
    `What do you like about it? <Q>My friends!<|>Not sure...</Q><*A>`,
    `Really? What is it you don't like? <Q> I miss my family... <|> Everything. </Q><*A>`,
    `No matter what, friends sure are important!!`,
    `You're not sure what it is? Well, as long as you like it!!`,
    `I didn't know you were one to get lonely so easily..`,
    `No way! This world has lots of perks!!`,

    `Is there a girl you like? <Q>Yes<|>Not telling!</Q><*A>`,
    `What's she like? C'mon, tell me! <Q>Sure<|>No way!</Q><*A>`,
    `Don't be so tight-lipped! C'mon, tell me! <Q>I dunno...<|>It's a secret!</Q><*A>`,
    `Wow! Really?! No way! ...You're not yanking my chain, are you??`,
    `I knew it... I'll get it out of you next time!!`,
    `Wait... Are you blushing? He blushin'! Ohhhh, he blushin'!!`,
    `Boo, you're no fun! It would've been better to just tell me....`,

    `What's a "vaccine"? Is it true that it hurts? <Q>It hurts!<|>It doesn't!</Q><*A>`,
    `Has getting one ever made you cry? <Q>Yeah<|>Nope</Q><*A>`,
    `I see! My friend told me they hate getting vaccinated! <Q>Really?<|>Me too.</Q><*A>`,
    `It hurts that much? I'm glad we don't have that stuff over here!!`,
    `You're a real tough guy, after all! You wouldn't cry!!`,
    `Wow, <&name>, you're pretty amazing! I'm seeing you in a whole new light!!`,
    `Makes sense... No one likes things that hurt, after all!!`,

    `What's a "summer break"? What's it for? <Q>Eating!<|>Taking it easy!</Q><*A>`,
    `So it's food? <Q>Totally!<|>Just kidding!</Q><*A>`,
    `Taking it easy? Like how? <Q> Going to the beach <|> Going to the mountains </Q><*A>`,
    `I see! I bet it's tasty... You're not lying, are you??`,
    `Oh, you're joking! You had me 100% fooled!!`,
    `Huh! Think you could find ocean Denjuu there??`,
    `So you go to the mountains and... play hide and seek? No??`,

    `Ghosts are scary, right? Are you scared of ghosts? <Q>Yeah<|>Nope</Q><*A>`,
    `Where can you find them? <Q>At graves<|>Inside trees</Q><*A>`,
    `What would you do if you met one? <Q>Run!<|>Dance!</Q><*A>`,
    `I'm feeling a bit creeped out... I don't think I can go home by myself now!!`,
    `Oh, so they suck up the sap... Wait, no, now you're talking about insects!!`,
    `So that's what you'd do? If you can't get away, though... Brrrr!!`,
    `You can do a nice little dance together! Wait... Ghosts don't have legs!!`,

    `Humans get something called "allowance", right? <Q>Yeah<|>I don't...</Q><*A>`,
    `What do you use yours for, <&name>? <Q>I save it!<|>Comics!</Q><*A>`,
    `I'm sorry, maybe I shouldn't have asked... <Q>Kind of...<|>It's fine.</Q><*A>`,
    `That's a surprise! I didn't think you were the type to save up....`,
    `Comics ain't bad, and hey, you can spend it on snacks too!!`,
    `Oh, sorry! I hope you're not mad at me....`,
    `You're not too worried about money, are you, <&name>??`,

    `Would you say you're smart? <Q>Why?<|>Hmm...</Q><*A>`,
    `You seem to know a lot about so many things! <Q>I guess.<|>Oh, pfft, me?</Q><*A>`,
    `Which is it? Are you smart? Or are you dumb?! <Q> Smart, maybe? <|> I dunno! </Q><*A>`,
    `I knew it! I have an eye for this sort of thing!!`,
    `What's up with you? That's more modest than usual!!`,
    `That's a bit vague, isn't it?! I really don't like it when people are vague!!`,
    `How can you not know? It's about you! Hm? Me? I'm smart for sure!!`,

    `Do you have a secret you can't tell anyone? <Q>I do<|>I don't</Q><*A>`,
    `What is it? Obviously you'll tell me, right? <Q>No way<|>Alright...</Q><*A>`,
    `Really? Are you 100% sure you can say you have no secrets at all? <Q>I am!<|>Maybe not 100%...</Q><*A>`,
    `It's that important to you? Man, now I REALLY wanna know!!`,
    `Uh huh... Mhm... Wow, really? I had no clue!!!!`,
    `Huh! Sorry for doubting you. Let me off easy this time!!`,
    `So you do have a secret after all. I knew it! You can't hide it from me!!`,

    `Is there anything you'd never forgive someone for? <Q>Yes<|>No</Q><*A>`,
    `There is? Will you tell me what it is? <Q> Lying! <|> Actually, there's nothing. </Q><*A>`,
    `Really? Nothing at all? You're so kind-hearted! <Q> Oh, not really. <|> You finally noticed? </Q><*A>`,
    `Lying, huh... I agree, that's pretty bad!!`,
    `What, really? You got my hopes up for nothing!!`,
    `You don't gotta be humble! Just be happy about it!!`,
    `You get a big head fast, don'tcha!!`,

    `Are you better at using your brain or your brawn? <Q>Brain<|>Brawn</Q><*A>`,
    `Really? No way! Like how? <Q> Studying! <|> I'm good at riddles! </Q><*A>`,
    `I knew it! So what's your specialty? <Q>Baseball<|>Fencing</Q><*A>`,
    `Wow, studying? I had you all wrong!!`,
    `I'm quite good at riddles myself! Surprised??`,
    `That's right, you're always wearing your helmet! I'd like to try and play baseball sometime too!!`,
    `No way. I don't believe it! If you thought you could fool me, guess again!!`,

    `I worry that I'm too shy... <Q>Don't worry<|>Yeah right</Q><*A>`,
    `I guess I'm worrying too much, huh? <Q>Yeah<|>To fix it...</Q><*A>`,
    `I'm serious! You don't understand my concern at all, do you... <Q>I'm sorry!<|>I don't</Q><*A>`,
    `Thank you! I feel a bit more confident now!!`,

    `I should speak my mind? You're right! Thanks!!`,
    `Sorry for getting mad... Gimme advice later, okay??`,
    `Asking you for advice was a mistake!!!!`,

    `I've thought this a while, but... you're pretty impatient, aren't you? <Q> You think so? <|> Says you! </Q><*A>`,
    `I do! You should slow down a bit! <Q>Got it!<|>Don't wanna!</Q><*A>`,
    `No, I've always been pretty easy-going! You should try to follow my lead! <Q>Fat chance!<|>I'll try!</Q><*A>`,
    `I'll try to take it easy too. To match you, you know!!`,
    `That sort of thing is exactly what I'm talking about!!`,
    `Fine then! You don't have to be so harsh about it!!`,
    `Thanks! I like that about you..`,

    `Are you calling your friends every now and then? <Q>I am<|>I'm not</Q><*A>`,
    `Everyone's waiting for you to call! <Q>Really?<|>I dunno...</Q><*A>`,
    `I thought so! You haven't called me in a while. <Q> Found me out, huh? <|> But I HAVE called! </Q><*A>`,
    `Yeah! They've all got a lot of things to talk about!!`,
    `I'm telling you, they are! What's so hard to understand?!!`,
    `You were bound to be found out! It's careless, y'know??`,
    `Noooo! Really? Maybe you did? I'll check my call log. Sorry!!`,

    `I've been sneezing like crazy lately! <Q> You've caught a cold. <|> You're allergic! </Q><*A>`,
    `Oh, so it's just a cold? How do I get rid of it...? <Q> Sleep a lot <|> Stay outside </Q><*A>`,
    `Allergic?! To what?! <Q>Being cool<|>Pollen</Q><*A>`,
    `That’s a great idea! I'll get warm and cozy and go to sleep straight away!!`,
    `What? That'll make me feel worse! Now you're just being mean!!`,
    `Ooh, you think I've gotten cooler recently??`,
    `Pollen? No way! I love plants! How could they do this to me?!!`,

    `Lately, I've been feeling watched... <Q> Someone's after you. <|> You worry too much. </Q><*A>`,
    `Why me?! I haven't done anything! <Q>It's fine<|>You sure?</Q><*A>`,
    `Do you think so? I'm too worried to sleep! <Q> Invite me over! <|> It's your imagination! </Q><*A>`,
    `How is it fine?! Take this seriously, please!!`,
    `Hearing that makes me worry that I did!!`,
    `Oh, I can have you over? Knowing that somehow makes me feel better!!`,
    `I'm telling you, it's not! I can't sleep! What do I do?!!`,

    `What should I do?! I accidentally deleted a close friend's number! <Q>Apologize<|>Live with it</Q><*A>`,
    `You're right... But what if they don't forgive me? <Q> Apologize anyway. <|> I don't care! </Q><*A>`,
    `This isn't something to brush aside! You're a cold- hearted one. <Q> Bribe them with a gift! <|> Lie! </Q><*A>`,
    `So I just need to give a heartfelt apology? I see. I'll try!!`,
    `You're giving up on me? What am I supposed to do if they don't want to be friends anymore?!!`,
    `That won't make them forgive me. What in the world should I do?!!`,
    `Say I deleted the wrong number? No way! I couldn't do that!!`,

    `I'm about to see an old friend for the first time in a long while! <Q> Sounds nice! <|> In a long while? </Q><*A>`,
    `Don't you have friends you haven't seen in a while? <Q>I do<|>I dunno</Q><*A>`,
    `They're really far away, so it's been incredibly difficult to meet! <Q> So you're thrilled? <|> Uh-huh. </Q><*A>`,
    `Go see them every once in a while. It'll cheer you up!!`,
    `Put yourself in their shoes! Being forgotten sucks!!!!`,
    `For sure! Yesterday I was so happy I couldn't sleep!!`,
    `That's not much of a reply... I'll let you off easy today, though!!`,

    `I found a rare treasure the other day! <Q>Nice!<|>Where?</Q><*A>`,
    `Right? It was really hard to find, too! <Q> What sort of thing was it? <|> May I have it? </Q><*A>`,
    `I can't tell you! <Q>Please?<|>Tightwad...</Q><*A>`,
    `One of those rugged, hard things! ...Understand??`,
    `No use asking! You'll have to look for it yourself!!`,
    `Well, since you ask so nicely... ...Oops, nope, I seem to have forgotten!!`,
    `Excuuuuuse me?! No way I'll tell you now!!`,

    `I haven't had much confidence as of late... <Q> How come? <|> About what? </Q><*A>`,
    `It's just... I used to think I was so awesome... <Q>Cheer up!<|>But you are!</Q><*A>`,
    `About Telefang! I feel like I just can't win! <Q>Lighten up!<|>You can't.</Q><*A>`,
    `You're right... No matter how much I worry, that's just the way it is!!`,
    `Am I? When you say it, I feel much more confident!!`,
    `You're right! You really are a good guy....`,
    `Right? I'm worthleeeess!!`,

    `If you could fly, what would you do? <Q>Go far away!<|>Not much</Q><*A>`,
    `When you say "far away", where do you mean? <Q>Anywhere<|>Somewhere</Q><*A>`,
    `Don't you have dreams?! <Q> I'm afraid of heights... <|> Lay off! </Q><*A>`,
    `I totally get that feeling! The sky sure is nice!!`,
    `What? You're a bit of a vague one, aren't you??`,
    `Oh, you're scared! That's serious, isn't it!!`,
    `What? Why? It's healthy to dream!!`,

    `If you could turn back time, how far would you go? <Q> To when I was a baby. <|> I wouldn't. </Q><*A>`,
    `Why a baby? <Q>No tests<|>Won't say</Q><*A>`,
    `Why don't you wanna go back? <Q> The present is fine <|> Because... </Q><*A>`,
    `Tests, huh... Being a human must be hard..`,
    `Why? No reason? Suspicious...!!`,
    `Oh! That's good! I think so too!!`,
    `You don't wanna forget your friends, huh. I hear ya!!`,

    `If you could have one wish granted, what would it be? <Q>Not telling<|>Can't decide</Q><*A>`,
    `Why not? Is it a secret? <Q> It won't come true! <|> Yeah </Q><*A>`,
    `Even so, you must have at least one! <Q> I can't think of one... <|> Actually... </Q><*A>`,
    `It doesn't come true if you tell others? Why's no one told me this?!!`,
    `Man, I was hoping you'd tell me. That's okay, though..`,
    `Come on, you've got to have some dreams! Like... hitting a home run!!`,
    `Uh-huh... Mhm... I see! Such a nice wish... I think I'll wish for the same thing!!`,

    `Recently I heard a story called "Momotaro"! <Q> I know that one! <|> Never heard of it. </Q><*A>`,
    `In that case, from what fruit was Momotaro born? <Q>A peach<|>An apple</Q><*A>`,
    `Momotaro fought alongside a monkey, a dog, and a duck! <Q>Huh!<|>...Huh?</Q><*A>`,
    `Corrrrect! I was wrong, though..`,
    `Nope! Too bad. You don't know it very well, do you??`,
    `Don't you feel like that's a bit off? Might just be my imagination..`,
    `Huh? Am I wrong? Oh, a pheasant, not a duck! I see!!`,

    `Have you heard the old story "Stone Soup"? It's my favorite. <Q>Yes<|>No</Q><*A>`,
    `How did the guy manage to make such a tasty soup...? <Q> With a tasty rock! <|> With everyone's help! </Q><*A>`,
    `It's about this guy who magically makes a tasty soup by boiling a rock! <Q> That's not right... <|> That's right! </Q><*A>`,
    `Yeah, the most flavorful rock in existence! ...C'mon, get it together!!`,
    `Oh yeah, now that you mention it! That explains why MY stone soup tasted like water..`,
    `No, I remember it clearly! Wonder where I could get a rock like that..`,
    `I got it right? Nice! I did my best to memorize the story..`,

    `Little Red Riding Hood is such a scary story! <Q>Is it?<|>It is!</Q><*A>`,
    `What, you don't know it? Okay so, which would you rather have: a big heart, or a big mouth? <Q>Big heart<|>Big mouth</Q><*A>`,
    `Right?! The wolf gets proper messed up in the end! <Q> You know your stuff. <|> Mhm, uh-huh. </Q><*A>`,
    `Right, so you can cherish me better! You're a real bro, you know that??`,
    `What, so you can eat me better?! I gotta get outta here!!`,
    `I've been all about fairy tales lately!!`,
    `Don't you "uh-huh" me! How's about a proper response?!!`,

    `Do you perhaps know the story called "The Tortoise and the Hare"? <Q>I do!<|>What's that?</Q><*A>`,
    `Reading it really does you good, doesn't it? <Q>How?<|>Maybe...?</Q><*A>`,
    `Whoa... I feel sorry for you... <Q> Tell it to me! <|> Give it a rest! </Q><*A>`,
    `It's got a good message! Even if you go slow, just take it step by step and you can win!!`,
    `Yeah! Read it again, why don't you??`,
    `Welp, guess I'll have to tell it to you then... Oh no... I've forgotten it!!`,
    `Don't get so angry. It's just a story!!`,

    `What's The Ugly Duckling about again...? <Q>No idea<|>A swan</Q><*A>`,
    `I remember as far as when the duckling grows up into a beautiful swan! <Q> That's the story! <|> Really? </Q><*A>`,
    `Yes! That! That's it! I knew I could count on you! <Q> No biggie! <|> Everyone knows it. </Q><*A>`,
    `Oh, that's where it ends? Ohhhhh, okay!!`,
    `What, you've never heard it? Not even once??`,
    `I think I'll have you tell me another story next time!!`,
    `Oh, come on! I told you, I kinda-sorta know it! Hmph!!`,

    `I'm head over heels for Thumbelina at the moment! <Q>Why?<|>No way...</Q><*A>`,
    `She's petite and adorable! You think so too, right? <Q>Yeah<|>Maybe?</Q><*A>`,
    `I'm serious! You don't get it? <Q>Not at all<|>Sort of...</Q><*A>`,
    `Thumbelina is all mine, though!!`,
    `Fine! I'll love her even if no one else understands!!`,
    `Well, I guess that's fine! You're you, and I'm me..`,
    `Don't say "sort of"! She's not just "sort of" cute!!!!`,

    `You know Beowulf, the folk hero? Didn't he have, like... a giant sword? <Q>Totally<|>I don't know him</Q><*A>`,
    `Yeah! And he uses it to beat up on... Grendel, was it? <Q> Grendel's mom, actually. <|> His gardener, actually. </Q><*A>`,
    `Ahhh... I'd like to tell you about him, but I'm not sure I'd do him justice. <Q> Give it a shot! <|> Best not, then. </Q><*A>`,
    `He beats up someone's mom?! I can't believe this guy....`,
    `What did the poor gardener ever do to Beowulf? Water him??`,
    `Okay, listen up! So he, uh... Sorry. I actually don't remember a thing..`,
    `Yeah, you're probably right... That's a downer....`,

    `Are you familiar with The Town Musicians of Bremen? <Q>Yeah<|>No</Q><*A>`,
    `It's a story about a pig, a dog, a cat, and a chicken, am I right? <Q> No, that's wrong! <|> That's not all of them! </Q><*A>`,
    `If I recall correctly, they made a sound like "oink woof meow bah-gawk". <Q> You got it. <|> Wait a second... </Q><*A>`,
    `Huh? Is it? How about a pig, a dog, a cat, and a monkey??`,
    `There was another one? A frog or something? A mouse??`,
    `I wasn't entirely sure! Is that actually right, though...??`,
    `"Hee-haw woof meow bah- gawk"? Oh, the first one was a donkey?!!`,

    `The Little Mermaid is such a fun story! <Q>It is!<|>Is it?</Q><*A>`,
    `In the end, she lived happily ever after with the prince! <Q>Right.<|>Did she...?</Q><*A>`,
    `Is it a sad story? How does it end again? <Q> She becomes seafoam! <|> She becomes human. </Q><*A>`,
    `I love happy endings. Hm? Was that wrong??`,
    `Yeah, I thought that sounded wrong. I mixed it up with another story!!`,
    `Oh yeah, that's what happened... That's way too sad..`,
    `Oh, okay! In that case, all's well that... ends well??`,

    `Cinderella is such a horrible story! <Q>Why?<|>I agree!</Q><*A>`,
    `It's just... Cinderella gets picked on the whole time! <Q> That's true. <|> But in the end... </Q><*A>`,
    `Right?! What happened to the poor pumpkin they used as a carriage?! <Q> Oh, that part?! <|> Exactly! </Q><*A>`,
    `I can't stand people who pick on the weak..`,
    `Sure, she gets to be happy in the end, but she's got it tough up until then!!`,
    `What do you mean? Respect your food!!`,
    `Makes you worry, right? Probably eaten by rats!!`,

    `The Emperor's New Clothes is such an amazing story! <Q>Amazing?<|>I guess.</Q><*A>`,
    `No one noticed until a kid yelled "he's naked", right? <Q> They noticed! <|> That's true. </Q><*A>`,
    `It is! That story really makes me think. <Q>Why?<|>You philosopher!</Q><*A>`,
    `They did? Why didn't they say anything, then? Weirdoes!!`,
    `The kid was the only one who noticed! Huh? No??`,
    `Because everyone thought only they were special!!`,
    `Aww, stop it. You're making me blush!!`,

    `Hey amigo, I'm comin' at ya with a question about "The Three Little Pigs"! How's about it? <Q>Hit me<|>On one condition</Q><*A>`,
    `A house of straw, and one of sticks. What was the last one? <Q>Sand<|>Bricks</Q><*A>`,
    `Condition? Whaddaya mean? <Q> Don't talk like that. <|> Let's hang out! </Q><*A>`,
    `Wouldn't it collapse immediately if it were sand??`,
    `I see! Finally, the mystery is solved. As expected of the great <&name>!!`,
    `Sorry, I've gotten used to it. Uh... G-Good day! ...No, this is impossible..`,
    `No time! I'm too preoccupied thinking about this!!`,

    `You! You're good at baseball, right? <Q>Yup!<|>Not really.</Q><*A>`,
    `In baseball, how many outs are needed for the teams to switch? <Q>Three<|>Five</Q><*A>`,
    `Why are you always carrying a bat around, then?! <Q> You got me... <|> It's decorative! </Q><*A>`,
    `Oh, right! Let me be the umpire next time!!`,
    `Five outs?! Doesn't that get a bit rough??`,
    `It's obvious! You won't fool anyone with a lie like that!!`,
    `Really? And I was sure you loved baseball....`,

    `Are you well-versed in golf, <&name>? <Q>Very<|>A bit</Q><*A>`,
    `Someone told me golf is a game for adults! <Q>That's right!<|>It's not!</Q><*A>`,
    `Basically, golf is just putting a ball in a hole, right? <Q>I guess.<|>It's hard!</Q><*A>`,
    `So it is, huh... It's not for me, then!!`,
    `Kids play golf too? Then I bet even I could play!!`,
    `If so, even I could do it! I'll start practicing today!!`,
    `It's easy! Just pick it up and walk to the hole!!`,

    `Football is hard! Why am I so bad at it? <Q>Your kick?<|>Practice!</Q><*A>`,
    `Yeah! It's gotta be my kick! Is yours good? <Q>Of course!<|>Not really</Q><*A>`,
    `Practice doesn't matter if I have no one to play with... <Q>That's not true!<|>Oh.</Q><*A>`,
    `Really?! Give me some pointers next time!!`,
    `That's a bummer. Let's keep practicing!!`,
    `I'd feel lonely practicing by myself. I think I'll pass!!`,
    `Practice with me next time!!`,

    `Is tennis really a sport for women? <Q>It sure is.<|>Nah!</Q><*A>`,
    `I can't believe there's a sport with that sort of discrimination! <Q> Wait, no, nevermind. <|> That's just how it is. </Q><*A>`,
    `Isn't it? What kind of sport is tennis, then? <Q> A lot of... hitting. <|> You rally the ball. </Q><*A>`,
    `What! Don't do me like that! I'm trusting you, y'know?!!`,
    `No! Never give up! Let's play tennis whatever they say!!`,
    `So you just pound away? I love that sort of thing!!`,
    `R- Rally? I've never heard that word. That's kinda annoying, man!!`,

    `Volleyball is my specialty! <Q>Wow!<|>Liar!</Q><*A>`,
    `Heh heh heh! No one can stop my sliders! <Q>Sliders?<|>Spikes.</Q><*A>`,
    `Don't believe me then! My spikes are magical. <Q> ...Show me. <|> I don't believe you. </Q><*A>`,
    `Huh? But in the book I just read... Agh! That's the wrong book!!`,
    `That's just an itty-bitty mistake! Everyone makes mistakes, y'know??`,
    `Um...! I... can't show you! But I'm not lying! Seriously!!`,
    `Whatever! Whether you believe me or not doesn't change the fact that my spikes rule!!`,

    `I wanna play basketball! <Q> Do that then? <|> Sure, let's play! </Q><*A>`,
    `Ouch! Harsh, much? Guess I'll have to play by myself, then... <Q> That was mean of me... <|> Yep. </Q><*A>`,
    `I thought you'd say that! Bring the ball over, then! <Q> I don't have one... <|> Don't you have one? </Q><*A>`,
    `As punishment, play with me! Get some friends together and come over!!`,
    `Noooo! If you won't play with me, no way!!`,
    `You don't? To be honest, I don't have one either!!`,
    `I lost it! And here I managed to get you on board...!!`,

    `All the cool kids play ping-pong, right? <Q>Definitely.<|>I dunno..</Q><*A>`,
    `What's the difference between ping-pong and table tennis? <Q> They're the same. <|> Different balls. </Q><*A>`,
    `It's sort of faded away, hasn't it. That's no fun! <Q>I agree!<|>I don't mind.</Q><*A>`,
    `Oh, so they're the same! Why the two names, then??`,
    `A big one vs. a small one? Really? I feel like I'm being messed with!!`,
    `Ping-pong should make a comeback!!`,
    `Yeah, I guess we've got better entertainment nowadays!!`,

    `Isn't rugby scary? The players slam into each other a lot, right? <Q> Yeah <|> Lots of injuries, too. </Q><*A>`,
    `They get so shaken up that they pass out! Why would they do that? <Q> Who knows? <|> Love of the game. </Q><*A>`,
    `What! No! I'd never play! ...Maybe I'm overreacting. <Q> No, it's messed up! <|> You're overreacting! </Q><*A>`,
    `"Who knows"? That tells me nothin'! I don't get what's so fun about it!!`,
    `I don't wanna see that. I'd be out cold just watching!!`,
    `Yeah, you get it! Everyone else said it's just me!!`,
    `I do have a tendency to bail out of Telefangs too....`,

    `Where do you go if you want to learn judo? <Q>A dojo.<|>A strip mall.</Q><*A>`,
    `Are there dojos everywhere? <Q> There are. <|> There aren't. </Q><*A>`,
    `I didn't call to listen to your lame jokes! <Q>Sorry...<|>Lame?!</Q><*A>`,
    `So even your neighbors run a dojo, then??`,
    `Argh! I wanna see the real thing!!`,
    `My jokes beat yours any day!!`,
    `Don't get mad! You really need to up your joke game..`,

    `I've got a question... Is kendo hard? <Q>Not at all!<|>Kinda!</Q><*A>`,
    `Think even I could do it if I wanted? <Q> Yeah! <|> Got a teacher? </Q><*A>`,
    `Argh, that sucks! I really wanna try kendo! <Q> I'll teach you! <|> Too bad. </Q><*A>`,
    `Cool! All I need is a set of armor and a sword... Wait, I don't have either!!!!`,
    `You can teach me! Huh? No? Come on!!`,
    `Yesss! Bring a sword from the Human World next time!!`,
    `Unacceptable! This is discrimination! I wannaaaa!!`,

    `What's so fun about tea ceremonies? Is the tea good? <Q> It's serene! <|> It's not very good. </Q><*A>`,
    `Serene? What's that? Explain it to me! <Q>Kerosene.<|>Not sure...</Q><*A>`,
    `It's not? How about the snacks on the side, then? <Q> They're great! <|> They're sweet! </Q><*A>`,
    `You put kerosene in the tea...??`,
    `Well, thanks anyway. Talk again soon!!`,
    `I bet people who do tea ceremonies are just in it for the snacks..`,
    `I don't really like sweet things....`,

    `I heard about this thing called "ikebana"... The "art of flower arrangement". What's that about? <Q> You give them life. <|> Don't ask me! </Q><*A>`,
    `Give them what now? Aren't flowers already alive? <Q> You plant them. <|> Hard to explain... </Q><*A>`,
    `Man... Ikebana's pretty confusing, huh. <Q> Guess so. <|> Sorry I couldn't help... </Q><*A>`,
    `Plant them?! The way I heard it, it's about cutting 'em up...!!`,
    `Sorry for asking such a difficult question!!`,
    `I wanted to try it, but I think I'll give up on that then..`,
    `You don't need to apologize. I still learned a lot!!`,

    `You know the camp song, "The Other Day I Met a Bear", right? <Q>Yes<|>No</Q><*A>`,
    `How'd the person get away from the bear again...? <Q> Climbed a tree. <|> Made lotsa noise. </Q><*A>`,
    `Then how 'bout I tell you about it? <Q>Sure<|>I'm good...</Q><*A>`,
    `Ohhh, a tree! In reality, though, bears can climb trees..`,
    `No, I just remembered, they definitely climbed a tree!!`,
    `So it's about a girl, and she meets a bear, but it was the other day, right? Then... er... I'm pretty sure some more stuff happens..`,
    `You don't want to hear it? It's a really fun song!!`,

    `/0x1341fe/<*A>`,

    `/0x110000/<*A>`,
    `/0x110002/<*A>`,
    `/0x110004//`,
    `/0x110006//`,
    `/0x110008//`,
    `/0x11000a//`,

    `/0x11000c/<*A>`,
    `/0x11000e/<*A>`,
    `/0x110010/<*A>`,
    `/0x110012//`,
    `/0x110014//`,
    `/0x110016//`,
    `/0x110018//`,

    `/0x11001a/<*A>`,
    `/0x11001c/<*A>`,
    `/0x11001e/<*A>`,
    `/0x110020//`,
    `/0x110022//`,
    `/0x110024//`,
    `/0x110026//`,

    `/0x110028/<*A>`,
    `/0x11002a/<*A>`,
    `/0x11002c/<*A>`,
    `/0x11002e//`,
    `/0x110030//`,
    `/0x110032//`,
    `/0x110034//`,

    `So... where's this "school of fish" I've been hearing about? <Q> Dunno <|> Nowhere specific </Q><*A>`,
    `It's gotta be somewhere, though, right? <Q>I guess<|>No</Q><*A>`,
    `So you're saying there could be a school of fish anywhere? <Q>Anywhere!<|>Well, mostly</Q><*A>`,
    `Right! Help me look for it sometime, hm??`,
    `No way! I'm not giving up! There's gotta be someone who's seen it!!`,
    `Oh, they're common? Suddenly I'm not as interested anymore....`,
    `Only in clean waters? I gotcha!!`,

    `I gotta say, Christmas music is pretty darn good. <Q>Why?<|>I guess</Q><*A>`,
    `It's, you know... exciting! Gets you all fired up! <Q> Oh yeah! <|> That's because... </Q><*A>`,
    `You don't like Christmas music? I love it to bits! <Q> Do you even know Santa? <|> I'm not into it. </Q><*A>`,
    `Yeah, you get me! There's just something about it..`,
    `Santa? Hold up, good kids get presents?!!`,
    `Santa? Who? What does this "Santa" do??`,
    `What! Why? Do you have bad Christmas memories??`,

    `When do people usually sing, ya think? <Q> When they're happy. <|> When they're sad. </Q><*A>`,
    `Oh yeah! If you sing when you're happy, you get even happier! <Q>Totally!<|>Also...</Q><*A>`,
    `Oh, I see, if you sing when you're sad, you'll forget about it. <Q>Totally!<|>Also...</Q><*A>`,
    `Now that you mention it, everybody loves singing, right??`,
    `What's that? Singing can help you make friends? I should write that down!!`,
    `When times are tough, you can always sing a song!!`,
    `Ahhh! Moving people's hearts! Song really packs an emotional punch, doesn't it..`,

    `Know what my favorite party trick is? Singing "Itsy Bitsy Spider"! <Q> You can sing that?! <|> Lame... </Q><*A>`,
    `Yeah! It's even brought some people to tears! <Q> Tears of laughter? <|> Were they moved? </Q><*A>`,
    `Whaddaya mean,"lame"?! It's all the rage lately! <Q> Really? <|> I had no idea </Q><*A>`,
    `Ow, rude! Of course not. It's because I'm too good at singing!!`,
    `Yeah! I've even made myself cry a few times!!`,
    `If you didn't even know that, I think you're the lame one!!`,
    `You gotta keep an eye on what's hip and happening!!`,

    `I recently learned a song called "Auld Lang Syne"! <Q>Nice!<|>Uh-huh</Q><*A>`,
    `What does "auld lang syne" mean? <Q>Old long sign<|>Old times</Q><*A>`,
    `What language is that, even...? <Q> You don't know? <|> Almost English </Q><*A>`,
    `They liked using long words back then, didn't they. It makes sense that their signs would be long..`,
    `Oh, I see! So it's like... "for old times' sake". That's beautiful..`,
    `Nope! I sing it all the time, but I have no idea what it means..`,
    `Aha, almost English, huh. ... That tells me nothing!!!!`,

    `Jack and Jill went up the hill... Do you know that old nursery rhyme? <Q>Yes<|>Vaguely</Q><*A>`,
    `After that part, they go fetch a "pail". What's a "pail"...? <Q>A painful nail<|>A bucket</Q><*A>`,
    `Is there another verse...? <Q>Yeah!<|>No idea</Q><*A>`,
    `Some kinda weapon?! Pretty hardcore for a nursery rhyme!!`,
    `Oh, a bucket! I had no idea!!`,
    `Huh! Write it down for me next time, please!!`,
    `I guess that's how most people are with nursery rhymes... It's like only knowing the chorus of a song!!`,

    `When do you sing "Happy Birthday" again? <Q>Birthdays<|>New Year's</Q><*A>`,
    `Happy birthday, dear <&name>♪ Happy birthday to you!♪ <Q>Nice singing!<|>Eh...</Q><*A>`,
    `Liar! I actually already know it's for birthdays! <Q>You fooled me!<|>Sorry</Q><*A>`,
    `Thank you, thank you. I do my best.♪<*A>>`,
    `What, it's not your birthday? At least gimme props for my singing voice..`,
    `Yeah, but then you tried to fool me, so we're even!!`,
    `Alright, alright, I forgive you....`,

    `Do you know what an "artist" is? Is it tasty? <Q>I know!<|>Not tasty, no.</Q><*A>`,
    `Tell me! I have no idea what it is! <Q> They make art! <|> Actually... </Q><*A>`,
    `It's not food? Is it a drink, then? <Q> No idea. <|> Nothing like that! </Q><*A>`,
    `Oh, okay! You sure know a lot, don't you??`,
    `You don't know either?! You don't gotta pretend....`,
    `Now I really wanna know. It might keep me up tonight!!`,
    `Not a drink either, huh... That's no fun at all..`,

    `If there's one thing I love in life, it's crenellations.<*A>`,
    `I had a feeling you were a fellow architecture-head! Where are your favorite crenellations? <Q>A castle<|>My house</Q><*A>`,
    `Pfft, you don't even know what crenellations are? Me? I know. Yeah, I know. <Q>Really?<|>Oh, okay.</Q><*A>`,
    `Mine too! Ooh, ooh! Next time, let's gush about fluted columns!!`,
    `Either you're full of it, or your family is filthy rich..`,
    `Of course! They're fancy buttery bread rolls, right??`,
    `Chin up, buddy! I'll tell you all about 'em next time!!`,

    `This is a touchy subject, but... have you ever hoodwinked someone? <Q>Yes<|>No</Q><*A>`,
    `You have?! You know weaselry is bad, right? <Q>I know.<|>Is it?</Q><*A>`,
    `Yeah, haha, of course. It's bad. No chicanery for you OR me. <Q> ...You plannin' something? <|> Exactly! </Q><*A>`,
    `Of course you know! Never give in to the temptation of the horn- swoggle, <&name>!!`,
    `What are you saying?! You a bamboozler or somethin'?!!`,
    `N– No way! I'm no honeyfuggler! I wouldn't flimflam a fly!!`,
    `That's what I love about talking to you: my wool stays firmly un- pulled over my eyes..`,

    `Have you ever felt disquietude, <&name>? <Q>...Disquietude?<|>Never!</Q><*A>`,
    `Indeed... I suppose it's not your typical deportment. <Q> What are you SAYING? <|> Right! </Q><*A>`,
    `I figured! You're still a kid and all. <Q> Kids get it too! <|> I'm an adult. </Q><*A>`,
    `Don't worry about it! If you don't know, I'd best not tell you....`,
    `...Do you even understand what I'm saying??`,
    `Kids lately have a lot on their shoulders, huh....`,
    `You don't gotta put on a front! You're still a kid!!`,

    `Are you telepathic...? <Q>No<|>Why do you ask?</Q><*A>`,
    `Oh, okay... I was gonna ask you to share your telepathy with me. <Q>Why?<|>It doesn't exist!</Q><*A>`,
    `I was just thinking I wanted to talk to you, and now we're on the phone all of a sudden! <Q>Obviously!<|>Wow, really?!</Q><*A>`,
    `I wanna know what it'd be like to read other people's thoughts!!`,
    `Telepathy isn't real?! I had no idea!!`,
    `Oh, because I called you. Right. That makes sense..`,
    `Crazy, right?! ...Huh? It's not??`,

    `Do you know what a "southpaw" is? <Q>Yes<|>No</Q><*A>`,
    `Then tell me! It's a person who's... <Q> Right-handed <|> Left-handed </Q><*A>`,
    `Sorry for the hard question. It's a type of bird! <Q> I never knew! <|> ...You don't know either! </Q><*A>`,
    `Too bad, that's wrong! You're not a big trivia guy, are ya??`,
    `That's right! So you DID know?!!`,
    `Yeah, it's a super-duper rare bird! It goes "PAWWW!""`,
    `Meh! I thought I'd get you for sure....`,

    `Could you tell me what it means to "beam"...? <Q>Sure!<|>I have no idea.</Q><*A>`,
    `Tell me, tell me! <Q>To smile!<|>To stare!</Q><*A>`,
    `So you're not much of a vocabularian either... <Q> No, I am! <|> I'm in primary school. </Q><*A>`,
    `Ohhh! To beam... is... to smile! I'm writing this down!!`,
    `...Really? "Staring with joy"? Is that a thing people do??`,
    `Oh, don't worry about it... We all have our strengths and weaknesses..`,
    `Primary schoolers are getting smarter and smarter, man! Step up your game!!`,

    `I learned a new word! "Dungaree"! <Q>Wazzat?<|>I've heard it</Q><*A>`,
    `I know the word, but I dunno what it means. <Q>I wonder...<|>...What.</Q><*A>`,
    `Do ya know what it means? I wanna know! Tell me! <Q>Denim<|>Loose bowels</Q><*A>`,
    `Right? We gotta look into this!!`,
    `Oh, come on! I'm as confuzzled as you are..`,
    `Oh, I see! I should ask you things more often!!`,
    `Ohhh, of course! It's like... dung-arrhea! ...Seriously though??`,

    `Ya wouldn't guess it, but I'm all about decorum! <Q>Decorum?<|>Like how?</Q><*A>`,
    `You know, like Ps and Qs? Don't be so uncultured! <Q> Explain? <|> ...Peas in queues? </Q><*A>`,
    `You know... Washing your face in the morning; things like that? <Q>I do that<|>And?</Q><*A>`,
    `Manners, man! Too hard for you??`,
    `Lining up is a kind of decorum, I guess, but veggies ain't that considerate! Agh, it's hopeless....`,
    `Do you wash your hands and rinse your mouth when you get home, too??`,
    `Not leaving your seat in the middle of a meal, I guess??`,

    `Someday, I wanna see an aurora! <Q>Me too!<|>Not happening</Q><*A>`,
    `It's like a dazzling rainbow- colored curtain, right?! <Q>Yeah<|>Nah</Q><*A>`,
    `Why not?! <Q> Wrong place. <|> You're broke. </Q><*A>`,
    `That's amazing! I'm trying to imagine it, but I can't!!`,
    `No? Not a curtain? Maybe it's more like a carpet??`,
    `What, you gotta be a cer- tain somewhere to see it? That sucks!!`,
    `Aw man, I'm all for being realistic, but you didn't have to go there....`,

    `<&name>! Help!!! It's bedlam over here! <Q>What's up?<|>Bedlam?</Q><*A>`,
    `It's straight-up pandemonium! <Q>Oh no!<|>Panda money?</Q><*A>`,
    `Bedlam! A brouhaha! Commotion, you know? <Q> Oh, I know! <|> Commotion? </Q><*A>`,
    `You actually knew the word "bedlam"?! Well you're no fun....`,
    `No, pandemonium! A big ol' hubbub? A major rumpus?!!`,
    `Don't even try with me! I heard you say "bad lamb"!!`,
    `Come ON! Now I forgot what I was even gonna say!!`,

    `We should hang out more! You're my nakama, y'know? <Q>Sure!<|>...Excuse me?</Q><*A>`,
    `I've been getting really into Japanese lately! <Q>Dude, wow!<|>Why?</Q><*A>`,
    `It's this untranslatable Japanese word. It means, like... "you're like a brother to me". <Q> ...You just translated it! <|> I don't know about that </Q><*A>`,
    `It's nothing to "wow" about! You could learn it too!!`,
    `I just kinda like how it sounds, you know??`,
    `Whoa. I translated the untranslatable? I should be a translator..`,
    `Yeah, well, I don't– I don't know about your FACE!!`,

    `/0x110140/<*A>`,
    `/0x110142/<*A>`,
    `/0x110144/<*A>`,
    `/0x110146//`,
    `/0x110148//`,
    `/0x11014a//`,
    `/0x11014c//`,

    `"The apple doesn't fall far from the tree"... Do you get that expression? <Q>Yes<|>No</Q><*A>`,
    `I see. Children grow up to be like their parents, huh. <Q>Exactly!<|>Do they?</Q><*A>`,
    `Does it means apples are like cats? They won't get beat up even if they fall? <Q>Exactly!<|>No, they will.</Q><*A>`,
    `So that's it! Thanks for helping me out..`,
    `I dunno. I just heard it from a friend..`,
    `Phew! That's a relief! I like a spotless apple..`,
    `Wouldn't that depend on the height of the tree...??`,

    `/0x11015c/<*A>`,
    `/0x11015e/<*A>`,
    `/0x110160/<*A>`,
    `/0x110162//`,
    `/0x110164//`,
    `/0x110166//`,
    `/0x110168//`,

    `/0x11016a/<*A>`,
    `/0x11016c/<*A>`,
    `/0x11016e/<*A>`,
    `/0x110170//`,
    `/0x110172//`,
    `/0x110174//`,
    `/0x110176//`,

    `I bought too many items... I'm living hand to mouth... <Q>Hand to what?<|>Oh?</Q><*A>`,
    `It means you barely have any money! I've had to work hard lately. <Q>Doing what?<|>I see!</Q><*A>`,
    `You know, they keep coming out with things I want, heh heh... <Q> How about not buying 'em? <|> I feel ya. </Q><*A>`,
    `I've been meticulously combing grassy spots for chiru....`,
    `Watch out for buying too much stuff!!`,
    `No way. I love shopping!!`,
    `Well, no use crying over spilled milk. I'll work harder!!`,

    `Man, I'm hungry... Although I do have a fruit here. <Q>Eat it, then!<|>But?</Q><*A>`,
    `I thought about it, but... it's bitter! It's a bitter fruit! <Q> Don't eat it, then! <|> But if it's all you have... </Q><*A>`,
    `Well, I'm completely lost on whether to eat it or not! <Q> Just eat it... <|> Is something wrong? </Q><*A>`,
    `Think that's best? Okay, I won't..`,
    `I guess. "Necessity knows no law", right??`,
    `Hey, put yourself in my shoes! I was hoping you'd understand....`,
    `It's a bitter-tasting fruit! I don't know what to do!!`,

    `Have you made any friends here in the Denjuu World? <Q>Yes<|>No</Q><*A>`,
    `Hmm... How many? <Q>Lots!<|>A few.</Q><*A>`,
    `Why can't you make friends? <Q> I don't know how... <|> I don't need them! </Q><*A>`,
    `Even if you make a lot of friends, let's be close, you and me!!`,
    `When you make more friends, introduce me to them!!`,
    `Not much to do about that, I suppose... Good luck, though!!`,
    `Don't say that! Friends are important!!!!`,

    `We're pals, aren't we? <Q>Yeah!<|>Are we?</Q><*A>`,
    `I'd say we're best friends, even! <Q> Of course! <|> I dunno about that... </Q><*A>`,
    `Well... let's be friends, then! <Q>Sure!<|>I don't wanna.</Q><*A>`,
    `From now on we're SUPER best friends!!`,
    `Eh?! What?! Why?! C'mon, let's be best friends!!!!`,
    `Yessss! I'll be your friend!!`,
    `What do you mean?! Ugh! Whatever!!`,

    `Hey, do you read Comic BomBom? <Q>Of course!<|>No</Q><*A>`,
    `Do you read it every month? <Q> Obviously! <|> Only sometimes. </Q><*A>`,
    `Come on, you gotta read it. <Q>Sorry...<|>I'll start</Q><*A>`,
    `Yeah! Let's both keep reading it every month!!`,
    `You should read it every month!<*A>>`,
    `I bet all your friends read it!<*A>>`,
    `It's a ton of fun!<*A>>`,

    `I bought a new cell phone! Nice, huh? <Q>Cool!<|>Huh.</Q><*A>`,
    `Maybe you should buy one too, <&name>? <Q>I will!<|>Maybe later.</Q><*A>`,
    `You don't want one? <Q>Not really...<|>I do!!!</Q><*A>`,
    `Yeah, buy one! The newest model!!!!`,
    `Oh come on, buy one!!`,
    `Now I really wanna know what phone you already have....`,
    `Oh, so you do want a new one? Let's go shopping sometime!!`,

    `Hey, <&name>, do you play baseball? <Q>I do!<|>Nah...</Q><*A>`,
    `Teach me sometime! <Q>Sure!<|>If I feel like it.</Q><*A>`,
    `Let's practice sometime, then! <Q>What?!<|>Count me in!</Q><*A>`,
    `Okay, then I've gotta buy a bat!!`,
    `Stop saying things like that and just teach me already!!`,
    `What do you mean,"what"! Practice starts at 6 in the morning!!`,
    `Sweet! Let's work hard at it!!`,

    `Have you learned a bunch of Denjuu names yet? <Q>Yep<|>Not yet</Q><*A>`,
    `How many, do you think? <Q> All of them! <|> All of my friends'! </Q><*A>`,
    `You know my name, right? <Q>Obviously!<|>Uh...</Q><*A>`,
    `Whoa! That's amazing, <&name>!!`,
    `I see. There are tons of others, so keep learning!!`,
    `Yeah, of course. I'd be shocked if you forgot..`,
    `Eh? That's a joke, right? Come on, tell me you're joking!!!!`,

    `Do you ever go back to the Human World? <Q>Yeah<|>No...</Q><*A>`,
    `What do you do when you go back there? <Q>Eat<|>Sleep</Q><*A>`,
    `Huh? Don't you go to school? <Q> I forgot about that!!! <|> Haha... </Q><*A>`,
    `Eat so you grow big and strong!!`,
    `You shouldn't sleep all day, you know!!`,
    `No way! That's real bad!!`,
    `Don't just laugh! You've gotta to go to school!!`,

    `Think I could become a Denjuu pop star? <Q>I think so!<|>No way</Q><*A>`,
    `When I do, you should be my manager! <Q>I don't know...<|>Sure!</Q><*A>`,
    `You're wrong! I totally can! <Q> I said you can't! <|> Haaahaha! </Q><*A>`,
    `Why? Are you embarrassed??`,
    `Thanks! Wish me luck!!!!`,

    `I guess it's just a pipe dream after all....`,
    `Okay, I guess I'll just give up, then!!`,

    `Guess what? I got a new pink case for my phone! <Q>Sounds cute!<|>...Pink?</Q><*A>`,
    `I know, right? Pink is totally in right now. <Q>I want one!<|>Really?</Q><*A>`,
    `<&name>, you got somethin' against pink? <Q> You bet! <|> Nah, it suits you! </Q><*A>`,
    `You want it? Too bad, it's mine! ♪♪`,
    `You been livin' under a rock? Pink is totally in fashion!!!!`,
    `Whaaat? Pink is awesome!!`,
    `Really? It does? Teehee... Thanks!!`,

    `There's an elder living in Tronco Village, right? <Q>Right<|>You sure?</Q><*A>`,
    `What was his name again? <Q> His name is Musa. <|> It's Mosa, remember? </Q><*A>`,
    `There totally is! Did you forget already? <Q> I didn't know! <|> Ohhh, right! </Q><*A>`,
    `Yeah, that was it! Thanks!!`,
    `Huh? Is that right...? Hmmm....`,
    `Didn't you talk to him...??`,
    `You remember now? But you don't remember his name, do ya..`,

    `Hey, that guy staying at the elder's house, is he your friend? <Q>Yep<|>Sort of</Q><*A>`,
    `Do you guys get along? <Q>We're best friends!<|>More or less</Q><*A>`,
    `You don't get along? <Q>Not really<|>It's so-so</Q><*A>`,
    `Huh, that must be nice! We should try being best friends too!!`,
    `Not as well as you get along with me, huh!!`,
    `Then why'd you come here together??`,
    `Hmm, I see..`,

    `I saw you the other day! You looked happy. <Q>Call out next time!<|>I'm not happy</Q><*A>`,
    `I did! You just ignored me, remember? <Q>Sorry about that<|>I didn't notice</Q><*A>`,
    `Why? Did something happen? <Q>Nothing special<|>Diarrhea</Q><*A>`,
    `So you avoided me on purpose!!!!`,
    `Alright, it happens. Next time!!`,
    `Phew! You got me worried over nothing!!`,
    `Geez, you shouldn't eat things that grow over there!!`,

    `I was just taking a walk outside, and I got a tan... <Q>Like a spray tan?<|>That's fine</Q><*A>`,
    `Not THAT bad! <Q>Aww.<|>Phew!</Q><*A>`,
    `I'm just thinking... maybe a tan doesn't suit me? <Q>It would<|>It wouldn't</Q><*A>`,
    `You just wanna see me colored all weird, don't you?!!`,
    `That's good? Does my normal skin color suit me??`,
    `Really? Do you reeeeally think so??`,
    `Only you would be so upfront about it. Thanks..`,

    `There are oceans and rivers in the Denjuu World too. Can you swim? <Q>Yep!<|>No, I can't</Q><*A>`,
    `Then you can make friends with all of the ocean Denjuu! <Q>Sounds great!<|>Nope, too scary</Q><*A>`,
    `No way! You won't be able to survive in the Denjuu World like that!!! <Q> I'm learning <|> I'll figure it out </Q><*A>`,
    `Yeah! Exciting, isn't it??`,
    `They're not that scary! Some of them are really nice!!`,
    `That's the spirit! Good luck!!!!`,
    `No, you need to practice! Agh! Don't blame me if you drown!!!!`,

    `I got in a fight with a friend... What should I do? <Q>Apologize<|>Ignore them!</Q><*A>`,
    `Will they forgive me, you think? <Q>I'm sure they will<|>Probably</Q><*A>`,
    `The cold shoulder, huh! <Q>Exactly!<|>Or something</Q><*A>`,
    `You're right! I'll try to apologize! Thank you!!`,
    `Probably? You don't think things through too much, do you??`,
    `Okay! I already don't care about them!!`,
    `What?! I'm counting on you here! Argh!!`,

    `Have you ever been in a car? <Q>Yes<|>No</Q><*A>`,
    `What sort of car? Was it faster than me? <Q>Faster<|>Slower</Q><*A>`,
    `I bet you wanna try it, then. <Q>Yeah<|>No, too scary</Q><*A>`,
    `That fast? I'd like to try racing against one sometime....`,
    `Hah! It's no match for someone of my caliber!!`,
    `Ooh, what sort of car? Sure gets you excited..`,
    `I'll tag along! It'll be fine!!`,

    `<&name>! Why don't you ever call me? <Q>I call all the time!<|>Who is this?</Q><*A>`,
    `Really? Oh... Sorry! <Q>Come next time<|>How could you?!</Q><*A>`,
    `You forgot me? That's horrible! <Q>Terribly sorry<|>Got you!</Q><*A>`,
    `Yeah, next time you call, I'll make sure to come! I'm so sorry!!`,
    `I'm so sorry! Forgive meeee!!!!`,
    `Waaah! How could you?! Waaah! Who'd wanna be your friend anyway!!`,
    `Agh! Don't scare me like that!!`,

    `I wanna go to the Human World. Bring me there! <Q>Tag along<|>No thanks</Q><*A>`,
    `Is it fun there? <Q>It is<|>Not at all</Q><*A>`,
    `Why not?! <Q>It's a scary place<|>It's a secret</Q><*A>`,
    `Wow... I wanna go....`,
    `Aww, that's a disappointment....`,
    `Whaaat? It's scary? I don't like that!!!!`,
    `Huh? What? What is it? Tell meee! Now I'm interested!!!!`,

    `Cough! Hack! I'm down with a cold! <Q>Are you okay?<|>Don't exaggerate</Q><*A>`,
    `Are you worried about me? How nice of you... <Q>Get well<|>Take some medicine</Q><*A>`,
    `I'm not exaggerating! I'm really sick! <Q>Sorry, sorry<|>Hmm...</Q><*A>`,
    `Thanks... I need to sleep now. Good night..`,
    `But it's bitter...!!`,
    `It's okay....`,
    `Ah... I'm getting a fever. I have to hang up now..`,

    `I was taking a walk in the forest, and some stuff fell out at me! <Q>Really?<|>Nice</Q><*A>`,
    `Really! Haven't you seen it? <Q>I haven't!<|>Ohhh, that?</Q><*A>`,
    `Nice, huh? You should go take a look in the forest too! <Q>Sure<|>Is there anything to find?</Q><*A>`,
    `You haven't? There's a good chance you will, I think..`,
    `Yeah, probably! Man, you almost missed it, huh??`,
    `Lemme know if you find anything!!`,
    `There totally is! Take a look around, huh??`,

    `<&name>, do you prefer sweet or spicy food? <Q>Sweet<|>Spicy</Q><*A>`,
    `Yeah, sweet stuff is great! <Q>Yeah<|>I love it!</Q><*A>`,
    `I can't handle spicy stuff... <Q>Why?<|>Don't be such a child!</Q><*A>`,
    `I'd like to try candy from the Human World sometime....`,
    `But if you eat too much, you'll get fat!!`,
    `It makes your tongue hurt!!`,
    `But... I AM a child!!`,

    `It's so hot here. I wish I could cool down... How are things over there? <Q> It's hot... <|> It's cool here </Q><*A>`,
    `It's hot over there too? <Q>A bit<|>Crazy hot</Q><*A>`,
    `That must be nice... <Q> No, it's freezing!!! <|> Yeah, it's perfect! </Q><*A>`,
    `Not much to do but hang on, I guess!!`,
    `It's crazy hot here too! I want air conditioning!!!!`,
    `I guess that's pretty bad too. Don't catch a cold!!`,
    `Wow, maybe I should head over there....`,

    `Phones have a lot of features nowadays... Have you gotten the hang of all of them? <Q>Completely!<|>Well, mostly</Q><*A>`,
    `Wow, that's amazing... I'm still learning. <Q>You'll never learn<|>You'll figure it out!</Q><*A>`,
    `I guess the basics are enough. <Q>Yeah<|>Never!</Q><*A>`,
    `Excuse me?! Just you watch! I'll become better than you!!`,
    `You really think so? I'm happy to hear you say that!!`,
    `Yeah! As long as you understand the important stuff, you're good!!`,
    `Not enough for you? Wow, I admire your enthusiasm for learning..`,

    `Have you been collecting items? <Q>Lots<|>A few</Q><*A>`,
    `Roughly how many? <Q>Many<|>A fair bit</Q><*A>`,
    `Make sure to seek out some more stuff, then! <Q>Nah...<|>Absolutely!</Q><*A>`,
    `Whoa! Can you even hold any more??`,
    `I hope you find more items!!`,
    `What are you saying?! Where's your spirit?!!`,
    `That's the spirit!!`,

    `Hey, do you drink coffee? <Q>Yep<|>Nope</Q><*A>`,
    `I don't! It's nasty and black and tastes bad! <Q>You're just picky<|>I guess</Q><*A>`,
    `Me neither. It's nasty, right? <Q>Adults drink it<|>It smells good</Q><*A>`,
    `So? It's not like it's good for you anyway!!`,
    `That's right! And it keeps you awake at night!!`,
    `Well, I'm not an adult yet!!`,
    `Yeah, the smell is pretty nice..`,

    `Hey, have you seen my litle brother? <Q>No<|>You have a brother?</Q><*A>`,
    `I see... I wonder where he could have gone? <Q>He'll be back<|>Did he run away?</Q><*A>`,
    `Huh? You haven't met him? <Q>Nope<|>What's he like?</Q><*A>`,
    `Maybe... but I'm worried, so I'll keep looking a bit longer..`,
    `Is he maybe... having family troubles?! Do you think so?!!`,
    `Then I'll have to introduce you sometime!!`,
    `Well, he looks just like me, so of course he's super cute..`,

    `I... I can't find my wallet!!! <Q> Did you drop it? <|> Was it stolen? </Q><*A>`,
    `I just don't know! Waaaah!!! <Q> Did you try looking? <|> Forget about it </Q><*A>`,
    `But who could have taken it?! <Q> Ask the police? <|> It's hopeless </Q><*A>`,
    `Huh? Wait... Here! I found it! I dropped it after all. Thanks!!`,
    `No way! I can't just give up like this!!`,
    `There's no police in the Denjuu World! Waaaah!!!!`,
    `Why would you say that?! I'm never asking you for support again!!!!`,

    `One of my human friends gave me a scarf! It looks awesome. <Q>What's it like?<|>Really?</Q><*A>`,
    `Well, it's black and slippery, and it smells like the ocean! <Q>That's seaweed...<|>Cool</Q><*A>`,
    `Yeah, it's super stylish! I'm gonna be the coolest dude in the Denjuu world! <Q>Sure<|>Good luck!</Q><*A>`,
    `Whaaat?! He was lying to me? That jerk!!`,
    `I know, right? Pretty stylish if you ask me. The smell is the best part!!`,
    `Hey, watch the tone! Meanie!!`,
    `Thanks! You'll see - I'll be the coolest for sure!!`,

    `I wanna get taller, so I'm drinking milk all day every day! <Q>Why?<|>You'll get sick</Q><*A>`,
    `Why?! Because being tall is way cooler! <Q>Really?<|>I suppose</Q><*A>`,
    `Now that you mention it, my stomach's been grumbling a lot... <Q>You should stop<|>Is that all you've done?</Q><*A>`,
    `Yeah it is! Obviously!!`,
    `Right? I'm not giving up!!`,
    `You'll never see me quit!!`,
    `Eh? I have to do things besides drink milk to grow tall? What?!!`,

    `How long have we been friends for, again...? <Q>A good while!<|>This is day 3.</Q><*A>`,
    `It's been that long? Have you made more friends since? <Q>Lots<|>Barely</Q><*A>`,
    `Really? I feel like we've been friends forever. <Q>Right?<|>It's just you</Q><*A>`,
    `I'm glad! But don't forget me, huh!!`,
    `You should make some more friends! The more, the merrier!!`,
    `Yeah! We go together like butter and broccoli!!`,
    `Whaaat? Are you telling me you don't like me??`,

    `Hey, you hit your head when you fell into the Denjuu World, right? Are you sure you're okay? Like, really REALLY sure? <Q>No sweat!<|>Still hurts...</Q><*A>`,
    `You're pretty tough, huh. <Q>Yup<|>You think so?</Q><*A>`,
    `If it still hurts, you should go see a doctor!!! <Q>No way<|>Alright</Q><*A>`,
    `Well, so long as you're alright!!`,
    `Yeah! I fall down all the time and it really hurts!!`,
    `Oh! Afraid of doctors, are ya? Heh..`,
    `Take care and make sure it gets better!!!!`,

    `Hey Punica, how's it going? It's me! <Q>Who?<|>Wrong number!</Q><*A>`,
    `"Who"? Ow, that's cold. What's up with your voice, by the way? <Q>I'm not Punica!<|>I have a cold, puni!</Q><*A>`,
    `Ahhh, sorry... <&name>? I must have gotten the numbers mixed up. <Q>Unforgivable!<|>It happens</Q><*A>`,
    `Ah, sorry! My mistake!!`,
    `Huh? You're not Punica, are you?! You really had me there....`,
    `Eek! I’m so sorry!!`,
    `Thanks. Next time I'll call you for real..`,

    `Sorry! I think I’m going to be late! <Q>To what?<|>Okay</Q><*A>`,
    `Huh? Then who was I supposed to meet today…? <Q>How should I know?<|>Another human?</Q><*A>`,
    `"Okay"? You mean you’re not mad? <Q>Why?<|>Late to what?</Q><*A>`,
    `Sorry! Sorry! Don't get mad! I'll call you later..`,
    `Nah! You're the only human friend I have, <&name>!!`,
    `"Why"? What? Huh??`,
    `You don't remember? Late to... uh... what was it again??`,

    `So I was wondering... when you're in the Human World, what do you do? <Q>Study<|>Play</Q><*A>`,
    `Study, huh. Is it fun? <Q>Yeah!<|>Not at all...</Q><*A>`,
    `Ooh! What do you do for play? <Q>Video games<|>Football</Q><*A>`,
    `Hmm... I wouldn't exactly call studying "fun"....`,
    `Figures. There's no way studying is fun, is there!!`,
    `Video games, huh... Nice... I'd like to try 'em sometime..`,
    `I know about that! That's the one where you use a ball! That's all I know, though..`,

    `My eyesight is bad... Maybe it's time to get glasses. <Q>You? Glasses?<|>Why not</Q><*A>`,
    `What! What's wrong with that?! <Q>Nothing...<|>Nothing!</Q><*A>`,
    `Think I'd look good in glasses? <Q>Totally!<|>*Snrk*</Q><*A>`,
    `I guess I wouldn't look good in glasses after all!!`,
    `You sure? Okay! I guess I'll get glasses, then!!`,
    `If you say so! I guess I'll get glasses!!`,
    `Wh-What's with the snicker? Are you making fun of me?!!`,

    `Hey... Where am I? <Q>Don't ask me!<|>Are you lost?</Q><*A>`,
    `I'm serious! I have no idea where I am! You have to help me out here. <Q>Don't boss me around!<|>Landmarks?</Q><*A>`,
    `I am! I was at my house just a few moments ago... Strange... <Q>Is there anyone there?<|>Wait where you are?</Q><*A>`,
    `Haha, sorry about that....`,
    `Hmm... Ah! Over there! I see the chimney of my house! Phew....`,
    `Oh! That's a good idea! If I see someone I know I'll tag along with them. See ya!!`,
    `Yeah! I'll wait here until someone comes to meet me..`,

    `I should try wearing clothes sometime! <Q>Sure<|>Nah</Q><*A>`,
    `I wonder what clothes would suit me. <Q>Anything<|>Hmm...</Q><*A>`,
    `Come on, it'd be great! I wanna try, at least. <Q>Okay, okay!<|>It wouldn't suit you.</Q><*A>`,
    `Really? Anything? I'll go for purple, then!!`,
    `What are you thinking so hard about? I bet you think I'm weird....`,
    `Heh heh heh! I'll show you!!`,
    `You can't say it wouldn't suit me until I've tried!!`,

    `Have you ever been to an amusement park? <Q>Yes<|>No</Q><*A>`,
    `What kind of food do they have? Is it good? <Q>It's not a restaurant!<|>Lots of different food!</Q><*A>`,
    `Let’s go to one together sometime! <Q>Sure<|>No way</Q><*A>`,
    `Whaaat! You go to an "amusement park" to play around, huh??`,
    `Lots?! Niiice....`,
    `Yesss! I'll wake up early!!`,
    `Do you hate amusement parks that much? Or do you just hate me???`,

    `Waaaah! I overslept! <Q>Were you up late?<|>That's no good</Q><*A>`,
    `Yep, I was up all last night playing video games. <Q>Don't overdo it<|>Study instead!</Q><*A>`,
    `Whaaat! I usually study, y'know. <Q>Really?<|>Oh, good!</Q><*A>`,
    `You're right! I'll try to be more careful!!`,
    `I was! ...I was just taking a video game break!!!`,
    `Well, aren't you rude?! I actually like studying!!`,
    `If there's ever anything you don't understand, I'll help you out!!`,

    `I'm into fortune telling right now. I'll give you a reading! <Q>Alright!<|>You can do that?</Q><*A>`,
    `Then I'll try to read your star sign! Hmm... You seem like a "Horn"! <Q>What's that?<|>Wrong!</Q><*A>`,
    `You bet! It's pretty accurate too! <Q>Cool!<|>...Really?</Q><*A>`,
    `Eh...? Oh I see, the zodiac is different in the Human World!  `,
    `No? That's weird... Then maybe you're a "Fang"??`,
    `Your lucky color today is indigo!!`,
    `Yes, really! I'm a magician by trade, didn't you know?!!`,

    `Heeelp! The Denjuu World is going to explode! <Q>What?!<|>No way</Q><*A>`,
    `A friend told me! <Q>They were messing with ya!<|>Huh...</Q><*A>`,
    `I'm serious! I've seen the omens! <Q>Can't be true<|>Oh nooo!</Q><*A>`,
    `Agh, now that you mention it, the guy did the same thing earlier!!!`,
    `You're calm about it? I'm so scared!!!`,
    `My predictions are never wrong!!!`,
    `It's terrible, right?! I'm getting the heck out of here! See ya!!`,

    `It's my birthday today! <Q>Congrats!<|>What, again?</Q><*A>`,
    `Thanks! How old do I look? <Q>3<|>45</Q><*A>`,
    `Huh? You think I said that before? <Q>Don't play dumb!<|>Maybe not?</Q><*A>`,
    `Hey, I'm not THAT young!!`,
    `Hey, that's mean! I'm obviously still a kid!!`,
    `Ahaha. Sorry!!`,
    `No worries! Now where's my present???`,

    `I've been learning karate recently! <Q>Wow!<|>For how long?</Q><*A>`,
    `Pretty cool, right? <Q>Karate?<|>You?</Q><*A>`,
    `I just said "recently", didn't I? <Q>Oh yeah<|>I didn't hear</Q><*A>`,
    `No, I'm talking about myself! I'm the cool one!!`,
    `Yeah! Call me next time you get in a Telefang!!`,
    `Is your memory going bad already? Pull yourself together!!`,
    `Bah! You're always like that! You should learn karate too; get some discipline!!`,

    `I wanna evolve too... <Q>Why?<|>Me too!</Q><*A>`,
    `I'd probably lose weight if I evolved, right? <Q>I don't think so...<|>You wanna lose weight?</Q><*A>`,
    `Wonder what you'd turn into if you evolved. <Q>I'd become an adult.<|>I'd become awesome.</Q><*A>`,
    `No? Really? I guess I should exercise, then....`,
    `Of course! My belly's been bulging a bit lately... Sigh....`,
    `Ohhh! An adult? Cool!!!!`,
    `Huh? Awesome? In what way??`,

    `I'm cooking right now! <Q>Nice!<|>Cooking what?</Q><*A>`,
    `Hee hee. If you can't cook, you'll never be popular, you know. <Q>That's your goal?<|>Really?</Q><*A>`,

    `Rice balls! My hands are getting all sticky, though. <Q>Eh.<|>Use water!</Q><*A>`,
    `Hee hee. Yeah..`,
    `Yeah! Everyone will like me!!`,
    `Hey! Respect the rice ball!!`,
    `Ohhh! I can put water on my hands, huh. Thanks!!`,

    `Chocolate is sweet, both literally and figuratively! <Q>Yeah!<|>I don't like it</Q><*A>`,
    `I could eat chocolate forever. <Q>You'll get cavities!<|>You like it THAT much?</Q><*A>`,
    `Why? It's so good! <Q>It's not!<|>I dunno.</Q><*A>`,
    `Don't worry! I take care to brush my teeth!!`,
    `Yeah! I could even eat it for lunch..`,
    `Well, that's how YOU feel..`,
    `You don't even understand yourself!!`,

    `I want a new cell phone strap. Do you have any nice ones? <Q>Sorry<|>Get your own!</Q><*A>`,
    `You don't? 'Kay then. Bye!!`,
    `Meanie! Forget you!!`,

    `People keep telling me I'm selfish!! <Q>Yeah...<|>You're not!</Q><*A>`,
    `You too, <&name>?! <Q>It's the truth<|>Got you!</Q><*A>`,
    `Thanks for being so nice... <Q>Cheer up!<|>Don't mind it!</Q><*A>`,
    `What?! There are people with egos wayyyyy bigger than mine!!`,
    `Geez... Don't scare me like that!!`,
    `Yeah! I feel better now!!`,
    `Okay! I won't worry what people say!!`,

    `Man, I'm exhausted... Gimme a piggyback ride! <Q>Where you at?<|>No way</Q><*A>`,
    `I'm right behind you!! <Q>Gah!!<|>Can't fool me</Q><*A>`,
    `Bah, look at scrooge over here... <Q>What!<|>Yeah, yeah</Q><*A>`,
    `Hahaha, got you! You're such a wimp. I'm off to tell everyone!!`,
    `Aw, that's no fun..`,
    `I won't depend on you for things like this again!!`,
    `Scroogey scroogey scrooooge!!`,

    `Don't move!! I dropped one of my contacts! <Q>Really?<|>It's not here</Q><*A>`,
    `Nah, I just thought I'd mess with you a bit. <Q>Uh-huh.<|>Would you need them?</Q><*A>`,
    `Right, it wouldn't be. I just wanted to brag about my contact lenses! <Q>You use contacts?<|>Bad eyesight?</Q><*A>`,
    `What do you mean,"uh-huh"! It was a joke! Blehhh!!`,
    `I've just been playing video games too much lately, so my eyesight's getting worse. Watch out for that, <&name>!!`,
    `I might be the only one in the Denjuu World with contacts! Aren't I great??`,
    `Recently it's been getting worse... Sigh....`,

    `Hey, do you have other friends of the same species as me? <Q>Yeah<|>I don't think so</Q><*A>`,
    `You do?! No way! You can't have friends other than me! <Q>I do though<|>Nonsense!</Q><*A>`,
    `Ah-hah, uh-huh. That's good. <Q>Why?<|>Don't be selfish</Q><*A>`,
    `No!! No wayyy!!!`,
    `Are you better friends with them, too? Darn it!!!`,
    `Because I wanna be your #1 best friend!!!`,
    `I'm not! This isn't enough to be called selfish!!`,

    `I just saw a bike over here... Can you ride a bike, <&name>? <Q>Of course<|>No</Q><*A>`,
    `You can? I wanna learn too, but it looks hard... <Q>It's easy!<|>Would your feet reach?</Q><*A>`,
    `Oh, okay. I hope you learn soon! <Q>Yeah!<|>I'm fine</Q><*A>`,
    `It is? Cool! Maybe I should try, then!!`,
    `Grr! Don't make fun of me!!!`,
    `I'll practice too! Keep at it!!`,
    `What are you saying?! You'd be so popular if you could ride a bike!!`,

    `I want a water gun... Do you have one, <&name>? <Q>I do<|>I don't</Q><*A>`,
    `Nice! Let me borrow it? <Q>Why?<|>It's mine!</Q><*A>`,
    `Let's go buy water guns together! <Q>Why?<|>I don't need one</Q><*A>`,
    `I'll use it to fight bad guys, of course!!`,
    `C'mon... Are you afraid I'll become even tougher than I already am??`,
    `Don't you wanna toughen up too??`,
    `You totally do, though!!`,

    `Have you made any T-Fanger friends? <Q>Yeah<|>No, none</Q><*A>`,
    `Cool. That's good. <Q>Yeah<|>Denjuu friends too!</Q><*A>`,
    `Wonder why you're not making friends. <Q>I'm shy!<|>You tell me.</Q><*A>`,
    `Don't forget your Denjuu friends, though!!!`,
    `Oho! Wonderful! That's the spirit!!!`,
    `That has to be it! Don't be like that! You gotta come on a bit stronger!!`,
    `I guess you just have to work on it a bit harder!!`,

    `I'm thinking about getting a part-time job at a shop. <Q>Can you do that?<|>Nice!</Q><*A>`,
    `I totally can! "That'll be 40 chiru. Do you want a bag with that?" <Q>That's great!<|>*Snicker*</Q><*A>`,
    `Hohoho, I think I'll save up and take a trip to the Human World! <Q>You can do it!<|>Why go there?</Q><*A>`,
    `Right?! It's a perfect job for this silken voice of mine..`,
    `Why are you laughing???`,
    `Yeah! I'll be such a good employee!!`,
    `Because I can go see the place where you live!!`,

    `How many models of cell phone are there in the Human World? <Q>Many<|>No idea</Q><*A>`,
    `Then there are probably super stylish ones too, right? <Q>Yeah<|>I dunno</Q><*A>`,
    `You don't have one? <Q>I do<|>I don't</Q><*A>`,
    `Wow, I want one... I guess I couldn't use it in the Denjuu World, though..`,
    `Next time you go to the Human World, look around a bit for me!!`,
    `Whoa! So with the D-Shot, you have 2 phones? That's so cool!!`,
    `Make sure to take care of your D-Shot, then!!`,

    `Is there good food in the Human World too? <Q>Yes<|>All food is good there</Q><*A>`,
    `So you do have tasty food? Like what? <Q>Meat<|>Veggies</Q><*A>`,
    `All food?! That sounds so good! <Q>Right?<|>I exaggerated</Q><*A>`,
    `Meat! Meat! I'm mad about meat!!`,
    `Vegetables?! No way! I hate those!!`,
    `Nice... I wanna try living in the Human World too!!`,
    `What?! Don't lie like that!!`,

    `Hey, what do you use to send text messages? <Q>The D-Shot<|>Willpower</Q><*A>`,
    `Ohhhh, I see! You text using your D-Shot, huh! <Q>Yep.<|>Probably.</Q><*A>`,
    `Pure willpower? Awesome! I don't think I can do that. <Q>Just kidding<|>You could!</Q><*A>`,
    `Thanks! I'll try for myself later!!`,
    `Hah! You don't know either, <&name>?!!`,
    `Huh? That's mean! I believed you!!`,
    `Alright, then I'll try right now! Hrrnngh.....`,

    `So, <&name>? I'm sorry about earlier. <Q>About what?<|>What do you want</Q><*A>`,
    `You don't remember? Oh, cool, nevermind then. <Q>...What?!<|>Oh, our argument?</Q><*A>`,
    `You're still mad? Come on, let's forget about it. <Q>Never<|>I'm not really angry!</Q><*A>`,
    `Oh, nothing! Laters!!`,
    `Agh, I was hoping you wouldn't remember... Let's be friends again!!`,
    `I already apologized! Geez!!`,
    `Oh geez, phew. Let's get along, huh??`,

    `Ahahahaha! Oh, <&name>? <Q>What happened?<|>Pipe down!</Q><*A>`,
    `I dunno! I ate some weird mushrooms growing over there and now I can't stop laughing! <Q>Oh, giggly shrooms!<|>How's your stomach?</Q><*A>`,
    `I can't... stop... laughing! <Q>About what?<|>I'll hang up!</Q><*A>`,
    `What's that? Eeheehee!!`,
    `Oh, totally fine! Ahahahah! I've got a strong stomach!!`,
    `I have no idea! Help meeeee!!!`,
    `No, wait!!!`,

    `Hey, <&name>! Sing with me! <Q>I'm kinda busy<|>Okay</Q><*A>`,
    `Awww, don't be like that... <Q>Maybe next time<|>Fine, just a little</Q><*A>`,
    `Awesome! Everyone else refused. I wonder why? LALALALALA.... <Q>It's horrible!<|>LALALALA♪</Q><*A>`,
    `Alright......`,
    `Yay!! Alright then, here we go!!`,
    `Huh? Did you say something??`,
    `Hey, you're pretty good!!`,

    `I wanna pick up a new skill.. What should I go for? <Q>Piano<|>Calligraphy</Q><*A>`,
    `Piano! That's perfect! <Q>Yeah!<|>It's hard, though!</Q><*A>`,
    `My handwriting's terrible, though... <Q>Oh.<|>Mental math, then?</Q><*A>`,
    `Okay, I'll go for piano, then!!`,
    `Nevermind then. I don't like difficult things..`,
    `I guess I'll start by improving my handwriting!!`,
    `That sounds like it could be useful!!`,

    `It sure would be nice if the Denjuu World had a bus... <Q>Yeah<|>Who would drive?</Q><*A>`,
    `I'd like to try riding a bus sometime. <Q>Haven't you?<|>It's convenient!</Q><*A>`,
    `Oh, yeah, someone has to drive... I guess I'll get a license! <Q>Good luck!<|>It's hard</Q><*A>`,
    `I haven't! I'm looking forward to it!!`,
    `Right? I can imagine..`,
    `Let's do this! I'm gonna provide the Denjuu World with bus rides!!`,
    `I'll start studying right away!!`,

    `Maybe I should go to school if I ever go to the Human World? <Q>Sure!<|>You don't have to.</Q><*A>`,
    `Wonder if I could make friends there. <Q>You wanna go to school?<|>For sure!</Q><*A>`,
    `Oh, I don't have to go to school? <Q>Only humans do.<|>You don't want to?</Q><*A>`,
    `Totally! I'll make so many friends!!`,
    `Do you trade phone numbers in the Human World too??`,
    `So I can skip school! I wanna show up for prom, though..`,
    `I just really don't like studying....`,

    `Aaaah! Save me!! <Q>What happened?<|>Run!!</Q><*A>`,
    `There's a cockroach heeeere! <Q>Cool<|>Waaah!</Q><*A>`,
    `I'm too scared! My legs won't move!! <Q>What is it?<|>Are you okay?</Q><*A>`,
    `Do something!!!`,
    `You're scared of them too?! You were my last hope!!!`,
    `A c-c-cockroach!!!`,
    `Nooooo!!`,

    `I just saw a monster around here! <Q>No way<|>Wow!</Q><*A>`,
    `I'm serious! I really saw one! <Q>What did it look like?<|>How big was it?</Q><*A>`,
    `"Wow"? Aren't you afraid of monsters? <Q>I'd like to see one<|>They're no prob</Q><*A>`,
    `It was long... and dark... and it said "mwaaaaooo"!!`,
    `Tiny..`,
    `What if you actually ran into one, though?!!`,
    `Man, you're cool... If anything happens, come save me!!`,

    `You haven't called me lately... Don't you like me? <Q>I don't<|>I do!</Q><*A>`,
    `Whaaat?! So I was right! What have I done? <Q>Nothing<|>Just kidding</Q><*A>`,
    `Why haven't you called me, then? <Q>I forgot!<|>I'll try to remember</Q><*A>`,
    `What's the problem, then?!!`,
    `Why are you always playing around with me? It's scary!!`,
    `Wha-! I'm that unmemorable?!!`,
    `Promise? Call me every now and then!!`,

    `Waaahh… *sniff* Waahhh! <Q>What's the matter?<|>Ooh, what happened?</Q><*A>`,
    `I got bullied again! <Q>Sigh. Again, huh.<|>Are you okay?</Q><*A>`,
    `Don't ask like you're about to hear a juicy story! <Q>Sorry...<|>It's not like that!</Q><*A>`,
    `Whaddaya mean?! I'm coming to you for help here!!`,
    `Yeah. Thanks, I feel better now..`,
    `Yeah, yeah... It's fine..`,
    `You're worried about me? I'm glad I'm friends with you, <&name>..`,

    `You have an animal called "panda" in the Human World, right? <Q>Yeah<|>You sure know a lot!</Q><*A>`,
    `What sort of animal is it? <Q>It's black and white.<|>It's a bear, sort of.</Q><*A>`,
    `I'm interested in animals in the Human World! <Q>Huh.<|>Wanna see one?</Q><*A>`,
    `Huh. That's kind of dull..`,
    `Is it big, then???`,
    `I'm gonna learn more about them than you!!!`,
    `Of course! I'll see one someday!!`,

    `Do you have a pet, <&name>? <Q>Yes<|>No</Q><*A>`,
    `Is it cute? <Q>Very!<|>Not very.</Q><*A>`,
    `Do you want one? <Q>Yes<|>Not really</Q><*A>`,
    `Keep giving it the love it deserves!!`,
    `Why? You've gotta love and cherish your pet!!`,
    `I want a pet too....`,
    `Don't you like animals? You don't hate Denjuu, do you??`,

    `So, <&name>, are you good at running? <Q>Totally<|>Not really</Q><*A>`,
    `Huh... I'm not too into running. <Q>Why?<|>It's fun!</Q><*A>`,
    `Me neither! I've gotten a bit pudgy lately, though... <Q>You've gotta get slim!<|>I know that feeling...</Q><*A>`,
    `I get so tired!!`,
    `What's fun about it? It's just fast walking..`,
    `I know, I know!!`,
    `If you can relate, I guess you need to lose some weight too!!`,

    `Skiing... Do you do that in a sandbox? <Q>Yes<|>No</Q><*A>`,
    `Oh really! I had no idea. <Q>I'm just messing with you.<|>Hee hee...</Q><*A>`,
    `Huh? Where do you ski, then? <Q>Snowy mountains<|>Hiking trails</Q><*A>`,
    `Oh, you joker!!`,
    `What are you snickering about??`,
    `Whaaaat! I can't handle the cold!!`,
    `That makes sense. If it were flat you couldn't move forward..`,

    `Hey <&name>, have you ever gotten in a fight with someone? <Q>Yes<|>No</Q><*A>`,
    `You have? Wow… <Q>You haven’t?<|>It happens</Q><*A>`,
    `Me neither! It's way too scary. <Q>Right?<|>It's best to get along.</Q><*A>`,
    `Of course not! It's scary!!`,
    `Why would you fight??`,
    `You wouldn't normally get into fights, y'know!!`,
    `Yeah! Let's get along, you and I..`,

    `Hey, you told everyone my secret! <Q>Did I?<|>It was a secret?</Q><*A>`,
    `Don't play innocent! I told no one but you! <Q>Everyone already knew!<|>Sorry...</Q><*A>`,
    `I trusted you! It was a secret!! <Q>You didn't say<|>Ha ha ha.</Q><*A>`,
    `Really? Am I the only one who didn't know??`,
    `Ugh! Whatever!!`,
    `But you can tell what's okay to say and what isn't, right?!!`,
    `This isn't something to laugh at!!`,

    `If you could be any Denjuu, what type would you be? <Q>Aquatic<|>Field</Q><*A>`,
    `I'd be a Field Denjuu. <Q>Why?<|>Think so?</Q><*A>`,
    `Yeah, me too! <Q>Really?<|>We're the same!</Q><*A>`,
    `Well, because I can't swim!!`,
    `Yeah! Otherwise I'd go all wrinkly!!`,
    `Totally! I like running, for example..`,
    `We go so well together!!`,

    `What are marshmallows like? <Q>White<|>Squishy</Q><*A>`,
    `They're white? <Q>Yes<|>Most often</Q><*A>`,
    `Are they alive? I heard they change size. <Q>If you heat them up.<|>They're alive!</Q><*A>`,
    `They sound tasty! I'd like to try one sometime..`,
    `There are others? Are there purple ones??`,
    `I see! I thought they could do it at will!!`,
    `Oh, they're animals? Creepy..`,

    `I wanna try going to school in the Human World! <Q>Whaaat?!<|>Wow!</Q><*A>`,
    `Huh? What's with the reaction? <Q>Do you study?<|>Sorry.</Q><*A>`,
    `Do you think that's cool? <Q>Yeah!<|>Mad respect.</Q><*A>`,
    `Yeah! Don't you like studying, <&name>??`,
    `Oh, you don't need to apologize or anything..`,
    `Maybe so?????`,
    `You're making me blush....`,

    `Have you heard of magpies? <Q>Yeah<|>Haven't you?</Q><*A>`,
    `What are they like? Are they tasty? <Q>It's an animal!<|>Not particularly tasty.</Q><*A>`,
    `It's a sort of pie, right? <Q>No<|>It flies</Q><*A>`,
    `Whoops, what a misunderstanding!!`,
    `So you’ve eaten one before??`,
    `Oh, I see! Is it a machine, then??`,
    `It flies? A flying pie??`,

    `Hello...? Can you hear me? <Q>Yeah<|>Hello?</Q><*A>`,
    `I guess the reception is bad here....`,
    `I wonder if it's because I'm underground??`,

    `What kind of animal is an "ostrich"? <Q>A bird<|>I don't know</Q><*A>`,
    `A bird, huh? What's special about it? <Q>It's huge.<|>Long eyelashes.</Q><*A>`,
    `It's got a scary-sounding name, though! <Q>Yeah<|>Does it?</Q><*A>`,
    `Bigger than me? Sounds scary....`,
    `Sounds cute!!`,
    `I'll bet there are ones that are 5 meters or taller!!`,
    `Maybe not??`,

    `Yo! Where are you?! You're late! <Q>I'm not meeting anyone!<|>Who is this?</Q><*A>`,
    `Huh? That's weird... <Q>Wrong person?<|>I'll just hang up...</Q><*A>`,
    `Hm? Right back at you! Who is this? <Q><&name><|>It's a secret!</Q><*A>`,
    `Probably. Sorry about that..`,
    `Yeah, whoops, sorry..`,
    `Agh, sorry, wrong number!!`,
    `Oh, oh, oh! I recognize that voice! It's <&name>, isn't it!!`,

    `I need to vent... My friend is playing hookey from our day out! <Q>Huh.<|>Hookey?</Q><*A>`,
    `Whaddaya mean,"huh"?! Don't you have anything to say? <Q>How awful!<|>Not really</Q><*A>`,
    `It means skipping something. <Q>That's no good!<|>Oh, cool!</Q><*A>`,
    `Am I right? It's just terrible!!`,
    `You're abandoning me too?!!`,
    `Right? 100% no good!!`,
    `This is no time to be impressed! Help me out here!!`,

    `Hello? Did you just call me? <Q>I did<|>Nope</Q><*A>`,
    `Sorry, I didn't notice in time!!`,
    `I wonder who it was then? Huh..`,

    `Geez! I can't believe it! <Q>What's the matter?<|>You sound angry.</Q><*A>`,
    `Get this: I let my friend borrow a toy, and he breaks it!! <Q>That's terrible.<|>Forgive him!</Q><*A>`,
    `Of course I'm angry! When else would I be angry?! <Q>You're always angry<|>Now</Q><*A>`,
    `I'm never talking to him again!!`,
    `Maybe if he apologizes..`,
    `No, I'm not!!!`,
    `Exactly! Now is when I'm angry!!`,

    `Some Denjuu can fly, while others can't. Are humans the same? <Q>We can't fly<|>Who knows?</Q><*A>`,
    `Really? So there are no humans that can fly? Wow... <Q>Is that bad?<|>Yup</Q><*A>`,
    `Haven't you seen a flying person? I guess they're rare, then. <Q>Exactly<|>Just kidding</Q><*A>`,
    `No, I didn't mean it like that!!`,
    `I guess that's why you have airplanes!!`,
    `Let's see if we can catch one sometime!!`,
    `Oh, they don't exist??`,

    `Oh man, I just saw a giant snake! <Q>How big?<|>I missed it?</Q><*A>`,
    `It was gigantic! Like, huge! <Q>Cool!<|>Really?</Q><*A>`,
    `Yeah! I really wanted to show it to you! <Q>Catch it for me?<|>Aw...</Q><*A>`,
    `Yeah! It was awesome!!`,
    `Does it sound like I'm lying??`,
    `No way! It was huge!!`,
    `Do you like snakes that much? I'll call you next time I see one!!`,

    `So, <&name>, are you a picky eater? <Q>Yeah<|>No</Q><*A>`,
    `What kind of foods do you like? <Q>Sweet<|>Salty</Q><*A>`,
    `Really? Impressive. <Q>Are you picky?<|>Can't waste food!</Q><*A>`,
    `Sweets are great aren't they....`,
    `Your tastes are so serious! You're not the flashy type, are you??`,
    `To be honest, I'm super picky!!`,
    `You're right. I'll try to eat up from now on!!`,

    `Hey, <&name>!! Do I seem like I have a short temper to you?! <Q>You're already mad!<|>Nope</Q><*A>`,
    `I'm not angry!! <Q>Yes you are!!<|>Sure...</Q><*A>`,
    `Right? I think seem pretty reasonable. <Q>Yup<|>I guess</Q><*A>`,
    `Why are you getting angry too?!!`,
    `Don't you give me a snide answer like that!!`,
    `Phew, I'm glad to hear that. Thanks..`,
    `You guess? What's that supposed to mean?!!`,

    `My friend isn't picking up the phone! <Q>I wonder why?<|>He's upset</Q><*A>`,
    `It's a bit worrying... <Q>Yeah...<|>Go check on him?</Q><*A>`,
    `H-Huh? You think he might be mad at me...? <Q>Nah, it's fine<|>Hmm...</Q><*A>`,
    `I hope he'll call me back....`,
    `You're right, I should go see what's up..`,
    `You really think so??`,
    `Eh? What are you thinking so hard about??`,

    `Hey <&name>, how're you doing? <Q>I caught a cold<|>I'm fine</Q><*A>`,
    `A cold? Are you okay? <Q>More or less<|>I'm dying</Q><*A>`,
    `I see. You're always full of energy, huh? <Q>Yup<|>You think?</Q><*A>`,
    `Try to get lots of rest before it gets any worse!!`,
    `You've gotta go to the doctor!!`,
    `I'm glad you're doing well!!`,
    `Yeah! I wonder, have you ever caught a cold??`,

    `Are you supposed to recycle empty cans...? <Q>Nah<|>Definitely</Q><*A>`,
    `Even though they're metal, you don't recycle them? <Q>You don't<|>Oh, whoops</Q><*A>`,
    `Oh, they're recyclable, huh. <Q>Yeah<|>Sort your trash!</Q><*A>`,
    `Are you SURE about that...??`,
    `I thought so! They're recyclable after all, huh..`,
    `I see! Thanks, man!!`,
    `Gotcha! I'll be proper about it!!`,

    `Yo, did I borrow a book from you? <Q>Yes<|>I don't think so</Q><*A>`,
    `Sorry, I need to keep it for a bit longer!!`,
    `Oh... I'll definitely return it next time I see you, then..`,

    `It costs money to use cell phones in the Human World, right? <Q>Yeah<|>I dunno</Q><*A>`,
    `Wow, that sounds terrible... <Q>Yeah<|>So I hear</Q><*A>`,
    `What do you mean, you "don't know"? <Q>I don't have one<|>You tell me</Q><*A>`,
    `Better be careful not to use it too much!!`,
    `You don't use one, <&name>??`,
    `I see. That saves on money, I guess..`,
    `Are you even listening to me...??`,

    `I'm so tired... <&name>, come get me. <Q>No way!<|>I'm hanging up!</Q><*A>`,
    `Pfft! I'll ask someone else then..`,
    `...<&name>? Hello? Heeey!!`,

    `I'm thinking about buying a new cell phone, so I'm saving up! <Q>Nice!<|>Just ask for one</Q><*A>`,
    `How much do you think I'll need to save? <Q>I dunno<|>A lot</Q><*A>`,
    `Do you always have people buy stuff for you, <&name>? <Q>Yeah<|>Not always</Q><*A>`,
    `Hmm. I'll have to think about it..`,
    `Yeah, I guess it's best to save up a lot..`,
    `You have to buy things yourself sometimes!!`,
    `Yeah, you can't just shift all your purchases onto others!!`,

    `I'm stumped. What kind of muffin is a "muffler"? <Q>A big one<|>It's a scarf</Q><*A>`,
    `Oh, so it's like a bigger muffin? <Q>Yeah<|>REALLY big!</Q><*A>`,
    `What? It's not a muffin at all? <Q>Didn't you know?<|>Do you want one?</Q><*A>`,
    `...Yo. Muffins are the best, so a big one's gotta be even bester!!`,
    `Wow! I wonder if I could eat an entire muffler on my own??`,
    `Man, I had no idea!!`,
    `I'd love to try one on! I think I'd like a yellow one....`,

    `Hey, thanks for earlier! I was thinking I'd do something in return. <Q>Yeah?<|>Don't worry</Q><*A>`,
    `What would be good to give you? <Q>Money<|>Anything's fine</Q><*A>`,
    `No, I insist! It's important to pay back your debts! <Q>Really?<|>It's fine!</Q><*A>`,
    `You'd take a friend's hard-earned money?!!`,
    `Alright, then get ready for my karaoke skills!!`,
    `Yeah, it's super important!!`,
    `You sure? Okay then. Thanks for being such a good friend!!`,

    `I saw inside your room! Man, you really need to clean!! up in there. <Q> When was this? <|> Sorry, I will </Q><*A>`,
    `Your mom showed it to me. <Q> Ask me first! <|> Whaaat?! </Q><*A>`,
    `If you don't keep it tidy, you'll never know where anything is! <Q> Okay. <|> How'd you get there? </Q><*A>`,
    `Aw come on, it was just a peek!!`,
    `Was there something you didn't want me to see??`,
    `Great!!!!`,
    `It's a secret!!`,
];
